### ISSUE TITLE
OCW Nginx should redirect ocw-origin to ocw.mit.edu in most cases

### ISSUE THREAD

**Issue by markbreedlove** [mitodl/salt-ops#1006]
At least one website has a link to OCW that uses the `ocw-origin` hostname: https://computerworld.com.br/2019/08/11/7-sites-que-oferecem-cursos-gratuitos-para-renovar-sua-carreira-em-ti/

We have fixed the issue with search engines indexing `ocw-origin`, but some traffic is still bypassing Akamai, and the bad URLs could be propagated.

We should expand [our nginx configuration](https://github.com/mitodl/salt-ops/blob/14d46780e4fd68340b964f272dcd4cd422066a76/pillar/nginx/ocw_origin.sls) and add `server` blocks so that the default `server` redirects to `ocw.mit.edu`, perhaps conditionally upon the client being outside of the MIT network, to facilitate testing.

**Comment by shaidar** [comment]
I'm assuming this can be closed right @markbreedlove?

**Comment by markbreedlove** [comment]
This is still an issue, but I guess it has been buried. I'll make a Trello card so I don't overlook this. That site referenced above still has a link to ocw-origin that does not get redirected.

**Comment by JoeMartis** [comment]
FWIW, this came up today. In the MIT Daily News, they are linking to our origin server https://ocw-origin.odl.mit.edu/courses/linguistics-and-philosophy/24-912-black-matters-introduction-to-black-studies-spring-2017/index.htm
