### ISSUE TITLE
Start shipping stdout and stderr logs for edX app and worker nodes

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#1007]
For the edX services the application logs typically elide the tracebacks which are most useful for our debugging purposes. We would like to start shipping the stdout/stderr logs that are stored under the supervisor directory to the Elasticsearch cluster.

**Comment by markbreedlove** [comment]
There are stderr logs for `cms` and `lms`, which seem useful and easy to parse.
There are also stderr logs for `forum`, but these have mixed line formatting, including lines with differently-styled timestamps. Are the forum stderr logs worth trying to ingest, too?

**Comment by blarghmatey** [comment]
We can ignore the forum logs this time around.
