### ISSUE TITLE
FluentD servers should have shorter Nginx log rotations

### ISSUE THREAD

**Issue by markbreedlove** [mitodl/salt-ops#1009]
The FluentD servers (`fluent1` and `fluent2`) rotate their Nginx logs weekly, and are supposed to keep 52 rotated logs. We've had the disk getting close to full recently on `fluent2.`.

Either make the servers' root volumes larger, or change the rotation to keep less on disk. A daily rotation would make it easier to free up space and to adjust disk usage.

**Comment by markbreedlove** [comment]
Related to #1022

**Comment by markbreedlove** [comment]
The volumes have been upsized, but it may still be better to have shorter rotation intervals and less retention.

**Comment by shaidar** [comment]
@markbreedlove Should we just close this?

**Comment by markbreedlove** [comment]
Yeah, I'll close it. I assume it's a better use of my time to get Vector rolled out, instead.
