### ISSUE TITLE
Set up SFTP service for OCW

### ISSUE THREAD

**Issue by markbreedlove** [mitodl/salt-ops#1011]
Set up SFTP for OCW staff to be able to upload files to the CMS 1 server.

Original ticket in Zendesk:
https://odl.zendesk.com/agent/tickets/34956

As noted in that ticket, there is [a constant in the CMS code](https://github.com/mitocw/ocwcms/blob/e4a9985bc0617ae13fb3611a48b0e7f125a42539/plone/src/ocw.types/ocw/types/config.py#L412) that defines the upload base directory to be `/files/OCWFileShare`. This is a symlink to `/mnt/ocwfileshare`, which does not seem like a suitable place to drop files. It's the base directory that contains other stuff like the engines directory and files owned by Plone. We need to figure out an ideal target for these uploads.

**Comment by markbreedlove** [comment]
@JoeMartis : Do people ever upload to anything other than the `Batches` subdirectory?

**Comment by pdpinch** [comment]
Joe chatted with the pub team and he believes the Batches subdirectory is sufficient.

**Comment by markbreedlove** [comment]
I'll call this done, now that I've added SSH keys for everyone we know about at the moment.
