### ISSUE TITLE
Update all formulas to use Salt on Python 3 and latest OS

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#1027]
Our formulas use Vagrant as a means of local development and testing in isolation. As they have been developed over the past >3 years there are varying levels of OS defined for the build boxes. We also need to make a concerted effort to run Salt on Python 3 for all of our infrastructure, so we need to iron out any issues on that front. To that end we need to do the following:

- [ ] Update all vagrant files to use latest OS (e.g. debian/jessie64 -> debian/buster64, etc.)
- [ ] Update script args to specify Python 3 installation (add `-x python3`)
- [ ] Build the vagrant boxes and identify errors. Anything requiring more than a 5 minute fix should be logged as a separate github issue in the relevant formula repo

**Comment by shaidar** [comment]
I'm assuming this is safe to close now as they've either been updated or we're not gonna bother as we move away from saltstack.
