### ISSUE TITLE
Environment Configuration Request - Zendesk Help Widget

### ISSUE THREAD

**Issue by asadiqbal08** [mitodl/salt-ops#1038]
#### Summary

Introduced a Zendesk help widget in Mitxpro project that is disabled by default. In order to enable it we need to set the `ZENDESK_HELP_WIDGET_ENABLED=True`

PR# [1190](https://github.com/mitodl/mitxpro/pull/1190)

Describe where/how to generate these new values

- `ZENDESK_HELP_WIDGET_ENABLED` - Boolean field. Just need to set it to `True` for enabling it.

#### Applicable Environments

- [x] Apply configuration to CI
- [x] Apply configuration to RC
- [x] Apply configuration to Production

**Comment by pdpinch** [comment]
@mitodl/devops I'd like to do some testing with the Customer Support team using RC before we turn it on in production.

**Comment by shaidar** [comment]
Pretty sure that this has been deployed.
