### ISSUE TITLE
Cherry-pick profiles fix

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#104]
When a user with no account logs in with CAS, their account is created automatically, but no profile is created. 

In Cypress, this generated annoying errors but did not otherwise block users. In dogwood this appears to prevent users from successfully logging in. 

The code to automatically create user profiles from CAS was merged in https://github.com/edx/edx-platform/pull/11988

**Comment by pdpinch** [comment]
They Cherry-pick seems to have changed the behavior, but I'm still getting errors. 

I was getting:

```
DoesNotExist: UserProfile matching query does not exist.
```

I'm not getting:

```
NoReverseMatch: Reverse for 'accounts_api' with arguments '()' and keyword arguments '{'username': u'c_1@touchstonenetwork.net'}' not found. 1 pattern(s) tried: ['api/user/v1/accounts/(?P<username>[\\w.+-]+)$']
```

I'm not sure if this might be a side-effect of using a Touchstone collaboration account to do my testing.

**Comment by pdpinch** [comment]
@itsbenweeks do you know anyone with a kerberos account who doesn't have an account yet on the qa stack? I'm concerned that they may run into this "NoReverseMatch" error similar to my Touchstone partner account. 

Maybe a new hire could be a guinea pig?

**Comment by itsbenweeks** [comment]
@pdpinch Can't we delete users from the Django Admin Panel?

**Comment by pdpinch** [comment]
> @pdpinch <https://github.com/pdpinch> Can't we delete users from the Django Admin Panel?

I suppose, but how will we know that there are users that need to be deleted? Or prevent them from signing up again?

**Comment by itsbenweeks** [comment]
I meant delete a user to then test the NoReverseMatch error.

**Comment by pdpinch** [comment]
> I meant delete a user to then test the NoReverseMatch error.
> 
Since edX did weird things with the django user, I wouldn't expect that deleting a user would do the right thing and delete the corresponding profile.
