### ISSUE TITLE
Discussion: Adjust OpsGenie alert priorities

### ISSUE THREAD

**Issue by markbreedlove** [mitodl/salt-ops#1044]
A significant majority of OpsGenie alerts come in at "Moderate" priority -- `P3`. These could be adjusted. Many of them are serious, and should be P2 (High) or P1 (Critical), whereas some of them do not require immediate action and could be P3 or even P4 (Low).

With more exact priorities configured, we should be able to have more context-appropriate alert routing.

What if we took most of the existing P3 alerts and moved them up to P2, and then selectively took ones that were safe to demote and moved them down to P3? We could amend our Elastalert settings (the low-hanging fruit) to send out alerts for QA or CI minions as P3 and production minions as P2 or P1. We could then follow up with Datadog and Sentry errors.

It's not clear to me from browsing through Sentry and Datadog how to configure priority levels for their alerts. Do either of you know how? That could be one reason that most alerts are at P3, which could be the default. Elastalert's configuration is more obvious, so that's why I think we might take a stab at it first.

What do you think?

**Comment by shaidar** [comment]
@markbreedlove Can this be closed?

**Comment by markbreedlove** [comment]
Yes, I did some of this months ago without updating this ticket.
