### ISSUE TITLE
FluentD POS file permissions

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#1049]
With the FluentD process running as a non-root user that means that it doesn't have permissions to create the `.pos` files under the directories where the source files are located. To address this issue without having to modify directory permissions across a variety of locations we should create a folder owned by the FluentD user that is used solely for storing the `.pos` files. Once that folder is present we can update all of our configurations to put those files in the shared directory.

**Comment by markbreedlove** [comment]
I've created this PR for `fluentd-formula`: https://github.com/mitodl/fluentd-formula/pull/12

From that PR:

> I considered creating a new directory to hold .pos files, but realized that some of the most typical files that need to be monitored are owned by root and not world-readable; and there are bound to be others. (Examples include the syslog files owned by root:adm in /var/log, and Apache and Nginx access logs, which are not world-readable by default in most Linux distributions.) Having root be the default user creates the least amount of extra work for the user of this formula.

**Comment by markbreedlove** [comment]
The approach mentioned just above has been abandoned in favor of creating the `.pos` file directory, after all. See https://github.com/mitodl/fluentd-formula/pull/13

We have specified in our pillar data that the FluentD user is to be `root` in most cases. It could still be useful to have `/var/lib/fluentd` for stashing the `.pos` files.
