### ISSUE TITLE
Deploy FluentD aggregators in operations-qa

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#1053]

**Comment by blarghmatey** [comment]
@markbreedlove it seems like this can be marked complete now, is that accurate?

**Comment by markbreedlove** [comment]
No, I only have it deployed with the heroku-syslog-http module commented out. There's an undefined constant error coming from within the module code that I'm trying to troubleshoot.

**Comment by blarghmatey** [comment]
What version is deployed on the aggregators? If it's newer than 0.14 then I would argue that those are part of the upgrade ticket which is a separate item. This ticket primarily pertains to getting the instances deployed and hooked up to Consul, so if that is complete then we can close this and concentrate efforts on #431

**Comment by markbreedlove** [comment]
Version 1.1.1 is deployed. I'll close this and add some notes to the #431.

**Comment by markbreedlove** [comment]
BTW, there are some log messages in the QA logging cluster, visible in the new Kibana.
