### ISSUE TITLE
Modify login page template for better UX when logging in with SAML

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#1059]
The current login page template gives priority to the username/password fields which we don't want to enable, meaning that the buttons for SAML login are small and subject to text overflow if it's too long. We want to make it easy for users to identify whether to use MIT Kerberos or Touchstone Collaborator accounts since we can't use the WAYF service via the direct SAML integration in edX.

**Comment by NotoriousMKD** [comment]
Can we change the label to say "MIT Kerberos" and "Touchstone Collaborator"? If that fits. That's more consistent with what is currently on prod and the language in our documentation for touchstone users.

**Comment by shaidar** [comment]
This was deployed.
