### ISSUE TITLE
Configure FBE to support course imports from edx.org

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#1061]
As an MITx ET, I'd like to be able to import courses from edx.org (which uses FBE) into studio.mitx.mit.ed (which does not use FBE) without modification. 

Currently, courses that are exported from edX can include content that limits access to "group 51". This is a side effect of FBE. When the course is imported into Residential MITx, group 51 doesn't exist and the content is hidden from all users. 

For example, the attribute `group_access="{&quot;51&quot;: [1, 2]}"` appears on a problem tag. 

See https://github.mit.edu/mitx/Spring-2020/issues/2 for some sample courses.

**Comment by pdpinch** [comment]
It seems like the easiest thing to do is to turn on FBE so that "group 51" behaves properly. However, there may be other side effects from turning on FBE.

**Comment by markbreedlove** [comment]
I spoke with @blarghmatey and I have enabled "Content Type Gating" and "Course Duration Limits," which are supposed to turn on the FBE feature.  My reference is https://discuss.openedx.org/t/how-to-enable-feature-based-enrollments-fbe/485. I have set the "enabled as-of" time to the past, per the post.

I will follow up with Meredith to ask if she can test it.

**Comment by markbreedlove** [comment]
This is deployed to production now.

**Comment by markbreedlove** [comment]
Whoah, sorry, wrong ticket ...

**Comment by markbreedlove** [comment]
Per Gabe Mulley's response to my question at https://discuss.openedx.org/t/how-to-enable-feature-based-enrollments-fbe/485/9 , we can not use Feature-Based Enrollments in our environment.
