### ISSUE TITLE
Update build scripts for Salt Master for HA deployment

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#11]
The salt master currently still has a few pieces of remaining state which prevent a fully automated and throwaway master build. Currently the relevant pieces of state are:
- [ ] GPG Secret key (used for decrypting pillar data)
- [ ] AWS SSH private key (used for bootstrapping EC2 instances)
- [ ] Mine cache (can be repopulated, difficulty here is if we need to run multiple concurrent masters)

**Comment by pdpinch** [comment]
Can this be done after the initial dogwood deploy?

**Comment by blarghmatey** [comment]
Yes, this is going to be pushed until after the deploy.


Regards,

Tobias Macey

Senior DevOps Engineer

MIT Office of Digital Learning

http://odl.mit.edu

On Monday, July 18, 2016 8:17:46 AM EDT Peter Pinch wrote:

Can this be done after the initial dogwood deploy?

**Comment by shaidar** [comment]
@blarghmatey Can this be considered complete?

**Comment by blarghmatey** [comment]
I think we can close this as we've gone a different direction
