### ISSUE TITLE
Research: Investigate options for load balanacing tier

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#1100]
The load balancing options offered by AWS are rather coarse and don't necessarily address our specific needs and use cases. We should investigate options for implementing a generalized load balancing tier to be used across our applications.

Some possible projects to explore:
- Nginx
- HAProxy
- Caddy
- Consul/KnotDNS

**Comment by shaidar** [comment]
Might be helpful when evaluating potential solutions to list our specific needs and use cases that AWS load balancing falls short in satisfying.

**Comment by blarghmatey** [comment]
Top of mind issues are:
- health checks are slow such that if an instance is not healthy the load balancer might continue trying to send traffic to it on the order of a full minute or more. Integrating with Consul health checks can provide faster route switching
- ELBs don't provide granular options for health checks per service and instead only offer host-based health reporting. This may be resolved by ALBs or NLBs but would likely be a better experience with something more purpose built. e.g. LMS, CMS, and GitReload services all running on edX boxes
- Having to have separate ELBs for every service is rather heavyweight
- Being able to set sticky sessions per-domain would be helpful, rather than the case with edX in which we have to have a separate ELB deployed for handling studio routes.
