### ISSUE TITLE
Research: Options for self-hosted PaaS

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#1101]
We have been bumping up against limitations of Heroku and could benefit from having an internal PaaS. This will require new primitives to update our options for deployment and maintenance. Some possible projects to explore and experiment with are:
- Nomad (Hashicorp)
- Kubernetes
- OpenShift
- Rancher
- Mesos

**Comment by shaidar** [comment]
I believe this can be closed now that we've settled on Nomad
