### ISSUE TITLE
Add HTTP beacon configurations for monitoring public availability of sites

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#1105]
In order to get early notice if any of our production hosts are experiencing downtime we want to run Beacons that will monitor for non 200 status codes and send alerts in the event that the sites are down.

The first pass of sites to monitor are:
- MITx residential
- OVS
- xPRO LMS
- xPRO app
- MicroMasters
- Discussions
- Reddit

**Comment by shaidar** [comment]
Deployed using Datadog's http-check
