### ISSUE TITLE
set ENABLE_INSTRUCTOR_LEGACY_DASHBOARD to true for draft and live servers

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#112]
We use the legacy dashboard to provide instructors access to the remote gradebook. 

With dogwood, the legacy dashboard feature flag now defaults to false. 

I suppose we only need it for the -live server, but for consistency and simplicity, we can turn it on for both.

**Comment by blarghmatey** [comment]
Addressed by #116

**Comment by blarghmatey** [comment]
@pdpinch This has been enabled now.

**Comment by pdpinch** [comment]
👍
