### ISSUE TITLE
Update generic secret mounts in Vault to use V2 API

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#1135]
The new releases of Vault have a V2 option for the generic secret backend which incorporates versioning of values which will be useful for us going forward. We should test out implementing this in QA and evaluate what other changes are necessary in our integration to make use of these new features.

**Comment by shaidar** [comment]
Appears like we should be easily able to upgrade based on this [link](https://www.vaultproject.io/docs/secrets/kv/kv-v2/)
