### ISSUE TITLE
View Unit in Studio Links do not work

### ISSUE THREAD

**Issue by itsbenweeks** [mitodl/salt-ops#115]
Somewhat related to #85, if I view courseware on the -live server then it's links to view unit in studio point to edx.org. Take a look at https://dogwood-qa-draft.mitx.mit.edu/courses/DevOps/0.001/2015_Summer/courseware/4695c7a6558c4e839c4bfd2e80ae810b/42fedafb26874e1fa8d0d81c74c2d269/ or other courseware components as an instructor/admin.

**Comment by blarghmatey** [comment]
Addressed in #116

**Comment by itsbenweeks** [comment]
Looks like this is still rendering with the old links. Should I wait a little longer for machines to provision?

**Comment by blarghmatey** [comment]
@itsbenweeks This is fixed now.

**Comment by itsbenweeks** [comment]
It's creating the proper links, but for some reason it is causing the system to shoot 500 errors.

Check out https://studio-dogwood-qa-draft.mitx.mit.edu/container/i4x://DevOps/0.001/vertical/0bb2079490104c818bcc2972a3291de9 for an example.

**Comment by pdpinch** [comment]
I assigned this back to @blarghmatey

**Comment by blarghmatey** [comment]
This is fixed now that version incompatibilities in sandbox are resolved. @itsbenweeks

**Comment by itsbenweeks** [comment]
These work great!
