### ISSUE TITLE
Studio "View Live" button redirects back to studio, if user hasn't logged into draft yet

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#127]
This is a bit of an edge case, but it through me. I've tested this in Firefox and in a Firefox private window. 

In a fresh session, before I've logged into draft (lms) with CAS, if I click the "View Live" button in studio (draft), my browser opens a new tab, negotiates with CAS and eventually opens up the same page in studio. 

Looking at headers, I think we're authenticating with CAS twice somehow.

After a session with draft (lms) has been established, this doesn't happen.

**Comment by pdpinch** [comment]
May be related to ZenDesk #3549

**Comment by blarghmatey** [comment]
@pdpinch Is this still an issue?

**Comment by pdpinch** [comment]
I'm still seeing it.

**Comment by pdpinch** [comment]
Closing this as we'll be upgrading shortly.
