### ISSUE TITLE
Run Ansible with Salt for EdX servers

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#13]
Write states for executing the EdX Ansible routines against a provisioned environment. This will include:

- [ ] Use Salt to populate necessary `vars` in Ansible
- [ ] Use Salt to run the Ansible process
- [ ] Tie in TestInfra state for verification

**Comment by blarghmatey** [comment]
Related to #31

**Comment by bdero** [comment]
#31 is a prerequisite for this work, it seems more closely related to #9 . The scope of #9 seems too big to be a story on it's own.
