### ISSUE TITLE
add --rm argument to ocw-to-hugo

### ISSUE THREAD

**Issue by gumaerc** [mitodl/salt-ops#1357]
In the `salt-ops/blob/main/salt/apps/ocw/templates/webhook-publish.sh.jinja` file,when running `ocw-to-hugo` it should be run with the `--rm` argument so it can remove the previous build's markdown output before running again.  Like this:

```
node . -i $SOURCE_DATA_DIR -o $COURSES_MARKDOWN_DIR \
    --strips3 --staticPrefix /coursemedia --rm >> $LOG_DIR/ocw-to-hugo.log 2>&1
```

**Comment by markbreedlove** [comment]
Fixed in https://github.com/mitodl/salt-ops/commit/e86652129e5319cb19541238ae195a4b67074d59
