### ISSUE TITLE
mitxonline: add Google Tag Manager settings for production

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#1462]
follow up to https://github.com/mitodl/salt-ops/pull/1458 but for production

The GTM tag is `GTM-M47BLXN`

**Comment by pdpinch** [comment]
@arslanashraf7 can you also review the GA tag settings in GTM, at https://tagmanager.google.com/#/container/accounts/6004402557/containers/51612754/workspaces/2/tags

**Comment by arslanashraf7** [comment]
> @arslanashraf7 can you also review the GA tag settings in GTM, at https://tagmanager.google.com/#/container/accounts/6004402557/containers/51612754/workspaces/2/tags

@pdpinch I took a look at the above GTM container and GA Tag variable and it looks good.
There was a slight difference between RC/Prod regarding how we defined our GA variable, so I replicated the separate variable format on RC, same as a prod to test and things work.

Additionally, I've created a PR for setting up the configuration in `salt-ops`. The PR also has the testing instructions which
 might come in handy for verification on Prod.

**Comment by arslanashraf7** [comment]
@pdpinch, Can this ticket be closed?

**Comment by arslanashraf7** [comment]
@blarghmatey, I think we need to reload the config for Prod since https://github.com/mitodl/salt-ops/pull/1463 has been merged but I still don't see GTM API requests on the production instance.

**Comment by blarghmatey** [comment]
This is deployed to production now.

**Comment by arslanashraf7** [comment]
@pdpinch I think we'll need to publish the container changes for production [here](https://tagmanager.google.com/?authuser=5#/container/accounts/6004402557/containers/51612754/workspaces/2). Let me know if I should do it for production or you'd like to do it yourself when needed.

**Comment by pdpinch** [comment]
Can you do it? I don’t think I know how. 

> @pdpinch <https://github.com/pdpinch> I think we'll need to publish the container changes for production here <https://tagmanager.google.com/?authuser=5#/container/accounts/6004402557/containers/51612754/workspaces/2>. Let me know if I should do it for production or you'd like to do it yourself when needed.

**Comment by arslanashraf7** [comment]
> Can you do it? I don’t think I know how.

@pdpinch I've published the container for production container and verified that Analytics URL e.g. (https://www.google-analytics.com/j/collect?..) is now being hit every time we load/visit a page which means we should be able to see the events against the production property created at https://www.google-analytics.com. 

I currently don't have access to that property on analytics so I couldn't see if the events are reflected in the Google analytics console as well or not.

**Comment by pdpinch** [comment]
I sent you an invite. I hope it was the correct property.

> I currently don't have access to that property on analytics so I couldn't see if the events are reflected in the Google analytics console as well or not.

**Comment by arslanashraf7** [comment]
> I sent you an invite. I hope it was the correct property.

@pdpinch I got the access and it was the correct property used for GTM production and i was able to verify the events and other statistics there. You might also take a look by visiting [this link](https://analytics.google.com/analytics/web/?authuser=1#/report-home/a5145472w286623989p251309700). 

Just for reference I'm attaching a screenshot of the captured page events:
<img width="526" alt="Screenshot 2021-09-23 at 5 48 13 PM" src="https://user-images.githubusercontent.com/34372316/134510292-b03c0210-e4df-45f6-9254-8407cab7309c.png">

I think we can close this ticket unless there is anything Devops want to add regarding this ticket.
