### ISSUE TITLE
Update template for not-logged-in users

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#148]
as reported by Ike

**Comment by bdero** [comment]
What needs to be done for this?

**Comment by pdpinch** [comment]
This is what I've been working on. I think we've got a good branch now, just need to squash.

**Comment by pdpinch** [comment]
fixed via https://github.com/mitodl/mitx-theme/commit/553bfafa96aa655262c7272ea1cac7fb8bbf2559
