### ISSUE TITLE
"View in Studio" button in staging.mitx.mit.edu links to studio-staging.mitx.mit.edu

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#149]
it should link to studio.mitx.mit.edu

the -staging stack should probably be retired, soon.

**Comment by pdpinch** [comment]
This may be a dupe of #158

**Comment by pdpinch** [comment]
@blarghmatey has this been fixed already?

**Comment by blarghmatey** [comment]
Yes this has been fixed and deployed.
