### ISSUE TITLE
Reddit nginx logrotation not working as expected

### ISSUE THREAD

**Issue by Ardiea** [mitodl/salt-ops#1508]
During vector configuration testing on a QA reddit server, I found that active logs were going to `error.log.1` and `access.log.1` rather than the `error.log` and `access.log` files as expected. That is weird and should be figured out. 

As a consequence of this, vector is not picking up any nginx logs for reddit.

**Comment by shaidar** [comment]
@Ardiea It's worth figuring out at some point, but I wouldn't spend too much time on the reddit instances, as those need to be retired as soon as the devs get a chance to use something else.

**Comment by Ardiea** [comment]
Just FYI I never got back to fixing this.
