### ISSUE TITLE
Drag and drop styling issues

### ISSUE THREAD

**Issue by bdero** [mitodl/salt-ops#153]
[![](https://s3.amazonaws.com/uploads.hipchat.com/151776/1096842/G4zYR8ov1h3Ujjn/upload.png)](https://staging.mitx.mit.edu/courses/DevOps/0.001/2015_Summer/courseware/4695c7a6558c4e839c4bfd2e80ae810b/a7cf01e88f434f19902033c811d1b469/)
(Click image to view problem in devops course on staging.mitx.mit.edu)

Tested on Firefox and Chrome.

**Comment by pdpinch** [comment]
@NotoriousMKD are you aware of any issues with the styling of drag-and-drop problems?

**Comment by NotoriousMKD** [comment]
@pdpinch Nope! I haven't seen this happen and haven't had any tickets come in about it.
