### ISSUE TITLE
env variable changes not being deployed to ocw-studio production

### ISSUE THREAD

**Issue by gumaerc** [mitodl/salt-ops#1557]
After https://github.com/mitodl/salt-ops/pull/1556 was released, the new env variables added in that PR were successfully deployed to RC but not production. I believe the expected behavior is that these releases happen automatically and that after merging the PR the deployment of the app using the Heroku enviornment should be updated upon release. If this is not correct, this issue can be closed but if not then we should fix it.

**Comment by blarghmatey** [comment]
That is not how it works unfortunately. The salt-ops code needs to have the `production` tag updated before the code will be included in production environments. I have done that for this change. Going forward we are going to be moving management of Heroku configurations out of Salt code and into Concourse pipelines where the workflow will be more intuitive and visible.
