### ISSUE TITLE
Display_name verticals not rendered in the templates any longer.

### ISSUE THREAD

**Issue by itsbenweeks** [mitodl/salt-ops#162]
At some point between dogwood and eucalyptus, the OLX attributes to display unit names changed. @jolyonb had mentioned that it would be helpful to cherry-pick this change, so that people co-authoring for MOOCs and our Residential system will not have to maintain these minute inconsistencies.

**Comment by pdpinch** [comment]
Since we are on Ficus now, I assume this has been addressed. 

@NotoriousMKD let me know if I'm wrong.
