### ISSUE TITLE
Install and configure Hubblestack

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#166]
hubblestack.io

**Comment by pdpinch** [comment]
?

**Comment by blarghmatey** [comment]
Sorry, I put this in as a placeholder so I could fill it out more.

Hubblestack is a tool built on top of Saltstack for doing security auditing of running systems. It includes things like alerting on file modifications, compliance auditing, etc. https://hubblestack.io/

**Comment by shaidar** [comment]
Ended up using a basic saltstack beacon to do FIM and deployed to rp.
