### ISSUE TITLE
Create new MITx devstack

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#173]
In order to support course authors we need to re-create the MITx devstack Vagrant box using the Ficus named release with the following changes:
- MITx Theme
- Host mathjax locally
- Reload course from disk button or have a script/app that does it

**Comment by pdpinch** [comment]
@shaidar can we close this?

**Comment by shaidar** [comment]
Created devstack build using packer, uploaded to S3 and provided access to a few folks.
