### ISSUE TITLE
enrollment e-mails sent from lms.mitx.mit.edu link to staging.mitx.mit.edu

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#176]
Steps to reproduce.

1. Go to the Instructor Panel / Membership for any course in lms.mitx.mit.edu 
2. Add an e-mail address to the batch enrollment form (does not need to be an mit.edu address)
3. Be sure "notify the user by e-mail is selected"

Expected behavior:

E-mail is sent to the user with links to the course on lms.mitx.mit.edu

Actual behavior:

E-mail is sent to the user with links to course on staging.mitx.mit.edu

**Comment by blarghmatey** [comment]
The LMS_DOMAIN variable was set to the wrong value in pillar data for instances with a role of edx-live. Updated and applied to servers.
