### ISSUE TITLE
Salt Shell

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#182]
Write a wrapper for the SaltStack CLI program(s) using python-prompt-toolkit. This can include features such as:

- [ ] Auto completion of execution modules and their functions
- [ ] Auto completion of minion IDs
- [ ] Auto completion of available grains
- [ ] On-disk caching of all completion options
- [ ] Enter a sub-prompt where all interactions are scoped to a particular minion
- [ ] Assignment of return values to local variables for manipulation in Python or chaining with subsequent calls

**Comment by shaidar** [comment]
Migrating from SaltStack. Closing
