### ISSUE TITLE
Update salt repos to support separate Forum instances

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#193]
Update the salt-ops states and orchestration to provision instances to run just the Forum service.

**Comment by pdpinch** [comment]
@blarghmatey is this still relevant?

**Comment by blarghmatey** [comment]
It's still relevant but not high priority. We can keep it as a tech debt or enhancement issue.

**Comment by shaidar** [comment]
Migrating from SaltStack. Closing
