### ISSUE TITLE
Add student module history database

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#195]
edX has created a new database schema for the student module history due to the size of the table. We need to create the schema and migrate the existing data over to it.

- [x] Create CSMH schema in MySQL
- [x] Configure edX to use new schema for writes and use dual read
- [ ] Migrate data to new schema
- [ ] Update configuration to use single read

Refer to http://edx.readthedocs.io/projects/open-edx-release-notes/en/latest/CSMHE/index.html

The relevant Ansible vars are:
```
EDXAPP_MYSQL_CSMH_DB_NAME: "edxapp_csmh"
EDXAPP_MYSQL_CSMH_USER: "{{ EDXAPP_MYSQL_USER }}"
EDXAPP_MYSQL_CSMH_PASSWORD: "{{ EDXAPP_MYSQL_PASSWORD }}"
EDXAPP_MYSQL_CSMH_HOST: "{{ EDXAPP_MYSQL_HOST }}"
EDXAPP_MYSQL_CSMH_PORT: "{{ EDXAPP_MYSQL_PORT }}"
```

**Comment by pdpinch** [comment]
@blarghmatey what's the status of this?

**Comment by blarghmatey** [comment]
We haven't done anything with it yet. I think it is something that we should do, but it's not top priority.

**Comment by pdpinch** [comment]
@blarghmatey what's the status of this?

**Comment by blarghmatey** [comment]
We have deployed the additional schema and updated the configuration to take advantage of it. The remaining steps are to migrate the existing data to the new schema and include it in our backups.

**Comment by pdpinch** [comment]
Is this something that we need to do for the Hawthorn release?

**Comment by blarghmatey** [comment]
The data migration can be done at any time. The tables are present already so everything will work. That being said, we can do the migration during the release.

**Comment by shaidar** [comment]
I'm pretty sure this is done now. Right @blarghmatey?

**Comment by blarghmatey** [comment]
We still haven't done the data migration which is why this ticket is still open.

**Comment by shaidar** [comment]
@blarghmatey Is this something we should plan on doing for the ironwood release?

**Comment by blarghmatey** [comment]
Yeah, let's plan for that. As part of it we should do the dump and load on QA to see how long it takes.

**Comment by blarghmatey** [comment]
This ended up taking over 4 hours for moving the data in QA next. We did not make this change in production. We will update the configuration in QA next to test the single read in order to validate functionality.

**Comment by shaidar** [comment]
@blarghmatey Did you end up doing this or is this something that we should plan for in the summer release?

**Comment by blarghmatey** [comment]
This is still using the dual read approach so we should add it to the list for summer.
