### ISSUE TITLE
Update automated notifications to use Slack instead of Hipchat

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#196]
There are a couple of notifications that are triggered by automated processes to deliver messages to Hipchat. Update them to use Slack.

- [ ] Elastalert mail delivery failure notifications
      Update pillar data to reflect proper configuration for Slack channel
- [ ] edX backup failures
      Update orchestration to use Slack module for `onfail` action instead of Hipchat

**Comment by shaidar** [comment]
[PR](https://github.com/mitodl/salt-ops/pull/197) submitted and merged.
