### ISSUE TITLE
Create PKI/CA infrastructure

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#20]
Having a CA/PKI setup will be useful for various infrastructure projects. Current examples include:
- Salt master key signing for HA and disposable salt master
- SSL key authentication between FluentD forward/aggregate nodes
- SSL key authentication for Kibana (?)

Potentially leverage https://github.com/cloudflare/cfssl

**Comment by blarghmatey** [comment]
This can be achieved more easily once we have a functioning installation of Hashicorp Vault as described in its documentation here: https://www.vaultproject.io/docs/secrets/pki/index.html

**Comment by pdpinch** [comment]
What's the status of this?

**Comment by blarghmatey** [comment]
This will be done after the dogwood deploy.


Regards,

Tobias Macey

Senior DevOps Engineer

MIT Office of Digital Learning

http://odl.mit.edu

On Monday, July 18, 2016 8:16:58 AM EDT Peter Pinch wrote:

What's the status of this?

**Comment by pdpinch** [comment]
Moving this to "New Issues" because I don't think we're ready to work on it?

**Comment by pdpinch** [comment]
I think this is done.

**Comment by shaidar** [comment]
Working on setting up Vault to have a PKI mount and issue signed certs for our infrastructure. I did test run on my local vagrant environment which was successful and then worked on getting the necessary certs to use on the production Vault. As part of that work, ended up upgrading our vault cluster to the latest version.
