### ISSUE TITLE
Add logging configuration for Consul servers

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#201]
Create a pillar file in `fluentd/consul.sls` in the pillars repository to configure reading and shipping the logs from Consul servers.

**Comment by shaidar** [comment]
Merged in [PR#57](https://github.mit.edu/mitx-devops/salt-pillar/pull/57)

**Comment by shaidar** [comment]
Syslog input plugin didn't work as I had expected it to. Consul servers are configured to send logs to syslog and I was under the impression that using fluentd's syslog input plugin, we'd be able to read the logs from syslog, filter the consul ones and ship them to fluentd, but that's not how the syslog input plugin actually works. So, will probably need to disable syslog logging in the consul config and simply use fluentd's tail input plugin.

**Comment by blarghmatey** [comment]
To clarify, if the intent is to tail syslog then the consul server configuration doesn't need to be modified. We just need to modify the fluentd configuration to tail the syllogism file and filter out the consul log lines.

**Comment by shaidar** [comment]
Merged in [PR#60](https://github.mit.edu/mitx-devops/salt-pillar/pull/60)
