### ISSUE TITLE
Review, reconfigure, and document notifications

### ISSUE THREAD

**Issue by shaidar** [mitodl/salt-ops#215]
Once we've centralized all the server logs, we should review and reconfigure some of the alerts and notifications. In some instances, we need to add some alerts to certain services and in others we need to tweak the current settings. 
In addition, we need to ensure that notifications are all funneled through the same system and then distributed to the appropriate channel (Email, Slack, SMS ...).
Last but not least, we need to document the process and possibly review Salt states to ensure that new builds are configured properly going forward.

**Comment by blarghmatey** [comment]
Can this be closed, or do we have remaining work for this ticket?

**Comment by shaidar** [comment]
Some changes were merged and a first pass at creating a [doc](https://github.com/mitodl/salt-ops/blob/master/docs/infrastructure/notifications.md) took place. Closing this issue for now.
