### ISSUE TITLE
Add logging configuration for CAS servers

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#221]

**Comment by shaidar** [comment]
Completed and code merged in [PR#59](https://github.mit.edu/mitx-devops/salt-pillar/pull/59). Following logs are now being shipped to fluentd aggregators:
- mitx shibboleth access and error logs
- cas django log
Added tagging to identify minion_id and environment as well. Tested by ensuring that logs are making it all the way through.
