### ISSUE TITLE
Create and schedule integration test for lmod proxy

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#230]
In order to ensure that lmod proxy is properly operational we need to write an integration test that gets run on a daily schedule and triggers an alert on failure.

**Comment by blarghmatey** [comment]
@shaidar this would be a good use case for monit

**Comment by pdpinch** [comment]
What's the status of this issue?

**Comment by shaidar** [comment]
The PR has been merged to have a status endpoint on lmod_proxy but I have yet to deploy it and test it on QA and prod. On my radar for this week.

**Comment by pdpinch** [comment]
Checking in on this again.

**Comment by pdpinch** [comment]
Any news on this?
