### ISSUE TITLE
Monitor critical services and notify on failure

### ISSUE THREAD

**Issue by shaidar** [mitodl/salt-ops#233]
Use saltstack beacons to watch the following running services on instances and trigger an event that would then notify slack when the service stops:
- fluentd
- edxapp:lms (roles:edx-dogwood-rp-live)

**Comment by pdpinch** [comment]
I'm curious to know what the status of this is?

**Comment by shaidar** [comment]
We setup pingdom to monitor web services however we still should be monitoring other services and think this should be part of the logging overhaul.
