### ISSUE TITLE
Migrate Heroku apps to new Dynos

### ISSUE THREAD

**Issue by shaidar** [mitodl/salt-ops#235]
kaggle-lti is using a legacy dyno and needs to be migrated to current dyno type before 4/3/17. 
There are other non-running apps that are using legacy dynos as well, and might be good to make a decision on possibly deleting/archiving them.

**Comment by pdpinch** [comment]
What are the non-running apps?

**Comment by pdpinch** [comment]
Kyle Boots (@indagation) should know more about when we can schedule downtime for kaggle-lti

**Comment by shaidar** [comment]
Non-running apps are:
- lmod-proxy
- lmod-proxy-ci
- lmod-proxy-qa
- mitx-cg-lti

**Comment by indagation** [comment]
Should be fine to have downtime whenever. The course isn't currently running and it starts back up in June.

**Comment by pdpinch** [comment]
These can all be destroyed.

We don't run lmid-proxy on heroku any more, due to time-out constraints.

mitx-cg-lti was test app for testing edX's LTI functionality.

**Comment by shaidar** [comment]
Deleted unused heroku apps and changed kaggle-lti from legacy dyno to pro dyno.
