### ISSUE TITLE
Distance Education - Migrate Lecture Capture

### ISSUE THREAD

**Issue by shaidar** [mitodl/salt-ops#242]
Distance Education is losing their server space and the entire process needs to be re-architected and moved to the cloud. Our job is to come up with a new design that satisfies current requirements and once approved, implement it no later than this summer. Additionally, archived material housed on the SAN need to be moved to cold storage.

**Comment by pdpinch** [comment]
This is done, except for moving the old data to cold storage. Elaine is working on moving data to dropbox (maybe not cold, but it is cheap)
