### ISSUE TITLE
Deploy a Business Intelligence reporting tool

### ISSUE THREAD

**Issue by shaidar** [mitodl/salt-ops#244]
There's a need to provide self-service access to a lot of the data that the engineering team has in order to make better and more informed decisions. Deploying a local instance [Redash](https://redash.io) appears to be a good solution based on the current needs and the fact that it can easily connect to a lot of our existing data sources.

**Comment by blarghmatey** [comment]
@pdpinch @Ferdi is there anything else that you would like to see completed before I close out this issue?
