### ISSUE TITLE
Task to delete stuck grade reports

### ISSUE THREAD

**Issue by shaidar** [mitodl/salt-ops#245]
We should probably write a script to run on a cron to scan the instructor_task table for jobs that are stuck in queueing for longer than x minutes and automatically delete them so that the instructor can retry the task. Prior to that though, it might be worth checking if this has been addressed in the new ficus release.

**Comment by blarghmatey** [comment]
@pdpinch is this still an issue at all?

**Comment by pdpinch** [comment]
I think we decreased the likelihood of this issue with several small changes (like including the problem id in the task name) but I think the potential is still there. 

Do we have any monitoring of stale tasks at all? Is there a best practice for this -- from edX or at large?

**Comment by blarghmatey** [comment]
I don't believe we've seen any more of these in recent memory. I'm inclined to close this issue and create a new one if the problem resurfaces.

**Comment by pdpinch** [comment]
Ok.
