### ISSUE TITLE
Write tests to verify connectivity of edX services

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#249]
Write tests to verify that the various pieces of edX can speak to each other and their respective storage systems. 
- [ ] xqueue can reach RabbitMQ and LMS and MySQL
- [ ] gitreload is up and listening
- [ ] xqueue-watcher can reach RabbitMQ and xqeuue
- [ ] celery worker is running and can reach RabbitMQ

**Comment by pdpinch** [comment]
Now that we have monit, are these more feasible?

**Comment by blarghmatey** [comment]
Yes. Some of these are addressed with the monit configuration that we have set up. @shaidar can you check off the items that are addressed?
