### ISSUE TITLE
Create a Sentry server for internal use

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#25]
@blarghmatey commented on [Mon Apr 04 2016](https://github.com/mitodl/configuration/issues/71)

**Comment by blarghmatey** [comment]
This will allow us to get better visibility and reporting into the error cases and patterns across our apps and stack.

**Comment by shaidar** [comment]
This might be something worth revisiting down the line, but isn't currently a priority or on the roadmap. Closing.
