### ISSUE TITLE
Configure NTPD to use Google time servers

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#279]
Google has recently made public a set of time servers that smear leap seconds so as to avoid issues with applications pertaining to the extra second. We should configure our NTP daemons to use these time servers.

**Comment by shaidar** [comment]
Given that Debian/Ubuntu moved to using systemd-timesyncd, should we just configure that service and add the google time servers to /etc/systemd/timesyncd.conf instead of continuing to use ntpd?
