### ISSUE TITLE
Create alert for RabbitMQ soft failures

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#303]
Occasionally the RabbitMQ cluster will enter a 'soft fail' mode where the service is running but clients cannot authenticate. This can lead to confusing errors due to Celery tasks and xqueue submissions not being able to function.

In order to identify and alert on this situation there may be some common log messages from Celery and xqueue about authentication failures that we can alert on using ElastAlert.

**Comment by pdpinch** [comment]
@shaidar based on yesterday's alerts, it seems like this is working now?

**Comment by shaidar** [comment]
Yeah think this is safe to close now.
