### ISSUE TITLE
Ficus: implement header

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#305]
#### Header
- Current Header
![header before](https://cloud.githubusercontent.com/assets/8322892/26509830/9245b222-4228-11e7-9cd6-ee7187a591b4.png)
- QA Stack Header
![header](https://cloud.githubusercontent.com/assets/8322892/26508054/1f6d1166-4221-11e7-87ef-bdf2c4ff38da.png)
https://mitx-qa-next.mitx.mit.edu/dashboard

**Comment by amir-qayyum-khan** [comment]
@pdpinch header looks good at https://staging.mitx.mit.edu/dashboard
<img width="978" alt="screen shot 2017-06-08 at 4 33 29 pm" src="https://user-images.githubusercontent.com/10431250/26926754-44e48e6e-4c68-11e7-9d1f-95d91271163f.png">

**Comment by amir-qayyum-khan** [comment]
@pdpinch can you made me admin of https://mitx-qa-next.mitx.mit.edu/

**Comment by amir-qayyum-khan** [comment]
opened PR https://github.com/mitodl/mitx-theme/pull/12

**Comment by amir-qayyum-khan** [comment]
fixed by mitodl/mitx-theme#12
