### ISSUE TITLE
Ficus: implement footer

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#306]
#### Footer
- Current Footer
![footer before](https://cloud.githubusercontent.com/assets/8322892/26509847/a6448640-4228-11e7-83f8-b82704aef47b.png)

- QA Stack Footer:
![footer](https://cloud.githubusercontent.com/assets/8322892/26508059/2542340e-4221-11e7-8dc3-6362b3f56e9b.png)
https://mitx-qa-next.mitx.mit.edu/dashboard

**Comment by amir-qayyum-khan** [comment]
@pdpinch footer looks good at @pdpinch header looks good at https://staging.mitx.mit.edu/dashboard https://lms.mitx.mit.edu/dashboard
<img width="985" alt="screen shot 2017-06-08 at 4 36 26 pm" src="https://user-images.githubusercontent.com/10431250/26926837-a52eadd6-4c68-11e7-9224-e77b7db8eb05.png">

**Comment by pdpinch** [comment]
Right. The footers on https://staging.mitx.mit.edu/dashboard and https://lms.mitx.mit.edu/dashboard are currently working with dogwood. 

We're upgrading to ficus and we need to migrate the footers to ficus. I'll send you the QA server addresses for ficus on Slack. 

@blarghmatey can give you the repo location for the theme files.

**Comment by blarghmatey** [comment]
The theme is located at https://github.com/mitodl/mitx-theme

There is a dogwood branch which is what is deployed on current production. The master branch has been updated to an extent to work with Eucalyptus, but it no longer works with Ficus.

**Comment by amir-qayyum-khan** [comment]
opened PR https://github.com/mitodl/mitx-theme/pull/12

**Comment by amir-qayyum-khan** [comment]
fixed by mitodl/mitx-theme#12
