### ISSUE TITLE
Ficus: Terms of Service

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#307]
#### Missing TOS
The Terms of Service link takes the user to a page that is missing the TOS.

- TOS Page
![tos page](https://cloud.githubusercontent.com/assets/8322892/26469759/307e1698-4169-11e7-990d-6d7281e67b41.png)
https://mitx-qa-next.mitx.mit.edu/tos

**Comment by pdpinch** [comment]
@NotoriousMKD Can you include on this issue what the content of the TOS should be? I think Sheryl has a draft (which she probably gave to me at one point).

**Comment by NotoriousMKD** [comment]
Final TOS from Sheryl: 
[Residential MITx Terms of Service Final.docx](https://github.com/mitodl/salt-ops/files/1052995/Residential.MITx.Terms.of.Service.Final.docx)

**Comment by amir-qayyum-khan** [comment]
made PR https://github.com/mitodl/mitx-theme/pull/13

**Comment by amir-qayyum-khan** [comment]
fixed by mitodl/mitx-theme#13
