### ISSUE TITLE
Ficus: add TOS link in studio footer

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#308]
#### Possible Missing Link
There is no TOS link in the studio footer. 

- Studio Footer
![studio footer](https://cloud.githubusercontent.com/assets/8322892/26508063/2e8ddc70-4221-11e7-8837-a4289d8b7cdd.png)
https://studio-mitx-qa-next.mitx.mit.edu/course/DevOps/0.001/2015_Summer

**Comment by amir-qayyum-khan** [comment]
@pdpinch do you want me to all mitx tos (that we use on lms)?

**Comment by amir-qayyum-khan** [comment]
for TOS we need to fix these flags https://github.com/edx/edx-platform/blob/master/common/djangoapps/edxmako/shortcuts.py#L84
