### ISSUE TITLE
Ficus: hide analytics tab and link to Insights

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#310]
#### MITx Insights
There is a mention of MITx Insights and an Analytics tab.
![instructor page mitx insights](https://cloud.githubusercontent.com/assets/8322892/26506906/1c56ace4-421c-11e7-856b-4ce75b9573b6.png)
https://mitx-qa-next.mitx.mit.edu/courses/MITx/Welcome_to_MITx/Training/instructor#view-course_info

The Analytics tab has a link to MITx Insights. That link takes you to a localhost error. 

- Analytics Tab
![mitx analytics insights](https://cloud.githubusercontent.com/assets/8322892/26506873/030cc8cc-421c-11e7-8c41-f17c3967e348.png)
https://mitx-qa-next.mitx.mit.edu/courses/MITx/Welcome_to_MITx/Training/instructor#view-instructor_analytics

**Comment by pdpinch** [comment]
I hope we can hide these with the theme.

**Comment by amir-qayyum-khan** [comment]
@pdpinch it seems [ANALYTICS_DASHBOARD_URL](https://github.com/edx/edx-platform/blob/master/lms/envs/common.py#L2805) is not None/empty

please see 
- https://github.com/edx/edx-platform/blob/master/lms/djangoapps/instructor/views/instructor_dashboard.py#L134
- https://github.com/edx/edx-platform/blob/master/lms/djangoapps/instructor/views/instructor_dashboard.py#L84

**Comment by pdpinch** [comment]
If it were empty, would the tab be hidden?

And if it has a value, what does it do??

@mitodl/devops what value are we using for `ANALYTICS_DASHBOARD_URL` ?

It would certainly be nice if we could link users to https://analytics.odl.mit.edu/ through this tab. However, that's a very different app than open edX insights, so if the connection is anything more than a href, it won't work and we should just omit the whole thing.

**Comment by amir-qayyum-khan** [comment]
@pdpinch  i tested on devstack, we can hide or show ANALYTICS with unsetting or setting url

**Comment by blarghmatey** [comment]
I updated this configuration parameter and the tab is now absent.
