### ISSUE TITLE
Ficus: Unable to Add a New Section or Subsection in Studio

### ISSUE THREAD

**Issue by NotoriousMKD** [mitodl/salt-ops#313]
Trying to add a new section or subsection in studio results in an error message and doesn't add anything to the course. 
![new subsection studio error](https://cloud.githubusercontent.com/assets/8322892/26798717/aaa1d97a-49ff-11e7-80e7-52d0ca6e0140.png)
https://studio-mitx-qa-next.mitx.mit.edu/course/DevOps/0.001/2015_Summer

There is no error adding a new unit.

**Comment by shaidar** [comment]
`Failed to load resource: the server responded with a status of 504 (GATEWAY_TIMEOUT) - https://studio-mitx-qa-next.mitx.mit.edu/xblock`

**Comment by pdpinch** [comment]
I'm a little dubious about the devops course right now. Can you share a link to another course where you're seeing this behavior?

**Comment by NotoriousMKD** [comment]
I tested it in this course: https://studio-mitx-qa-next.mitx.mit.edu/course/MIT/MKD101/2017T2.

What I see now in both the Dev Ops course and my test course MKD101 is that I get the same error message, but when I go back to my course outline, the sections and subsections _are_ added. I guess it's timing out but still adding/modifying the content.

The same thing happens when I try publishing a unit as well. When I created the issue, I hadn't pushed the publish button for the unit, so I probably couldn't have actually added a unit in the first place.

Also, I get this error when I try to edit or delete any component, but the content does update when I refresh the page. 
 
To recreate: 

1. Visit https://studio-mitx-qa-next.mitx.mit.edu/course/MIT/MKD101/2017T2
2. Add a section or subsection, or publish a unit, or try to edit or delete a section/subsection/unit.
3. Wait...see error message.
4. Refresh page or course outline and see that the changes have actually taken place.

**Comment by shaidar** [comment]
This should now be fixed. I verified it by going through the steps mentioned to recreate the problem. The issue was that the credentials for the rabbitmq user had expired and needed to be renewed. Also noticed that the ttl on the user creds were set to expire every 24 hours, so we changed that to a longer period.
