### ISSUE TITLE
Ficus: New Studio Course Creation Error

### ISSUE THREAD

**Issue by NotoriousMKD** [mitodl/salt-ops#314]
Creating a new course in studio results in a time out error but adds the course to the Studio dashboard (similar to behavior in [issue #313](https://github.com/mitodl/salt-ops/issues/313)). However, trying to access the course throws an error that the page could not be loaded.
![creating a studio course error](https://cloud.githubusercontent.com/assets/8322892/26832423/66ccfc0e-4a9d-11e7-88ae-d7e1df90cdb9.png)

The course I created this morning is https://studio-mitx-qa-next.mitx.mit.edu/course/course-v1:MITx+mkd.000+2017_Summer 

To recreate: 

1. Visit https://studio-mitx-qa-next.mitx.mit.edu/home/
2. Click the `+New Course` button
3. Submit the form via `Create` button
4. Wait for time out error message
![studio new course time out](https://cloud.githubusercontent.com/assets/8322892/26832930/fb1e0708-4a9e-11e7-9b3b-a34ca1e4ae1f.png)
5. Refresh the dashboard
6. Click on your course link
7. Get error message
![creating a studio course error](https://cloud.githubusercontent.com/assets/8322892/26832423/66ccfc0e-4a9d-11e7-88ae-d7e1df90cdb9.png)

**Comment by shaidar** [comment]
I believe this is similar to [Issue#313](https://github.com/mitodl/salt-ops/issues/313) and the timeout issues. I successfully created a new course and did not encounter any timeout issues.
