### ISSUE TITLE
Ficus: cherrry-pick "Return only error value to students when codejail raises an exception"

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#321]
This is a small PR that we submitted upstream for Jolyon and the Physics department. 

https://github.com/edx/edx-platform/pull/14591

**Comment by blarghmatey** [comment]
This has been merged into the mitx/ficus-1rc1 branch of mitodl/edx-platform but not yet deployed.

**Comment by pdpinch** [comment]
@blarghmatey can this be closed?

**Comment by blarghmatey** [comment]
Yes, I was just leaving it open because it hadn't been deployed yet.
