### ISSUE TITLE
Add webhook endpoint on log aggregators for Re:Dash events

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#343]
In order to maintain an audit trail of actions in Re:Dash we need to log any action where one individual is granting permissions to another. Re:Dash has a setting to set the webhooks where events are sent, which includes a `grant_permission` event. To track these events we need to configure a new route on the log aggregators to accept these events via HTTP from the redash server and log them to an appropriate index in ElasticSearch. As a follow on we should configure an elastalert trigger to notify us whenever a `grant_permission` event happens.

**Comment by pdpinch** [comment]
Can you add a pointer to the docs on this? I'd be interested to know what other webhooks are supported.

**Comment by blarghmatey** [comment]
I didn't find any docs on this yet, I looked in the code and found the event, then zoomed out to the configuration parameter. In terms of support, it's anything that can receive and process a JSON payload.
