### ISSUE TITLE
Ficus: "View in Studio" Button Doesn't Work

### ISSUE THREAD

**Issue by NotoriousMKD** [mitodl/salt-ops#349]
On the LMS site, the `View Unit in Studio` button doesn't load Studio. 

To recreate:

- Visit a page on LMS (https://mitx-qa-next.mitx.mit.edu/courses/course-v1:DevOps+0.001+2015_Summer/courseware/4695c7a6558c4e839c4bfd2e80ae810b/8e4edd6685db4fc4b1db98020928318c/)
- Click the `View Unit in Studio` button
- Be taken to blank page 
![blank studio page](https://user-images.githubusercontent.com/8322892/27748214-901e238c-5d9c-11e7-874f-e41da16f76ad.png)

Here's a gif showing this behavior: https://cl.ly/2L3q133R1V3Z
I checked this issue in another course as well.

**Comment by blarghmatey** [comment]
@NotoriousMKD were you able to replicate this in other modules in the DevOps course and other courses? I just tested the `view in studio` link on the electromagnetics course and it worked properly for me.

**Comment by NotoriousMKD** [comment]
@blarghmatey I see the same error when I use the `view unit in studio` button in my test course (https://mitx-qa-next.mitx.mit.edu/courses/course-v1:MITx+mkd.001+course/info) but you're right, I just tried it in 8.371 (https://mitx-qa-next.mitx.mit.edu/courses/MITx/8.371/2017_Spring/info) and it worked properly. I've created a couple of test courses on the QA stack, and the `view unit in studio` isn't working in any of them. It's working in all of the older courses that I've checked just now. The DevOps course doesn't fit that pattern exactly because it was created a while ago, but I do notice that the DevOps URL has the + signs instead of / that the older courses have.

**Comment by pdpinch** [comment]
One thing that I remember that confounds testing of this feature is that the behavior may depend on whether you are currently logged into studio. 

See if you can tell whether the "View in Studio" button is directing you to the correct link and then see if you can actually arrive there. 

It might also help to test in a private window.

**Comment by blarghmatey** [comment]
Based on the comment from @NotoriousMKD I think this may be similar to the issue facing us with git logs.

**Comment by pdpinch** [comment]
Not going to fix this.
