### ISSUE TITLE
elasticsearch returner on salt master generates errors

### ISSUE THREAD

**Issue by shaidar** [mitodl/salt-ops#357]
When configuring elasticsearch returner (/etc/salt/master.d/returner.conf) on salt-master, the following error is logged:
`[salt.utils.event ][ERROR   ][7761] Could not store events - returner 'elasticsearch.event_return' raised exception: too many values to unpack`
This appears to be a known [issue](https://github.com/saltstack/salt/issues/20826) and one way to resolve it is to define a mapping template.
To test the issue and/or verify a fix, run the following command:
`salt <minion> test.ping --return elasticsearch`

**Comment by blarghmatey** [comment]
We have given up on the elasticsearch returner due to the number of issues that it has caused.
