### ISSUE TITLE
Add configs for forum logs in FluentD

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#366]
We are currently not shipping the forum logs so we need to add some configs to send those to ElasticSearch

**Comment by pdpinch** [comment]
@mitodl/devops is this still an issue?

**Comment by shaidar** [comment]
As far as I can tell, this is still an issue.

**Comment by shaidar** [comment]
Forum logs live in `/edx/var/log/supervisor/forum-std{out,err}.log` and at first glance appears that each one has a slightly different logging format.

**Comment by shaidar** [comment]
The format of this log file still appears to be inconsistent in hawthorn release.

**Comment by shaidar** [comment]
This still appears to be an issue in `koa`
