### ISSUE TITLE
Ficus: Hide User Name Dropdown Options

### ISSUE THREAD

**Issue by NotoriousMKD** [mitodl/salt-ops#383]
The username dropdown includes options that we don't want to show.

On LMS and Staging, we don't want give access to Profile and Account:
![user name dropdown](https://user-images.githubusercontent.com/8322892/28794493-83ddc804-7604-11e7-95aa-5fe4c0a400fb.png)
https://lms.mitx.mit.edu/dashboard

On Studio, we don't want to give access to Maintenance. 
![studio maintenance](https://user-images.githubusercontent.com/8322892/28794540-aa533afa-7604-11e7-9a84-8d75812de2b7.png)
https://studio.mitx.mit.edu/home/

**Comment by pdpinch** [comment]
Has this been released, or was it just closed b/c the PR was merged?

**Comment by blarghmatey** [comment]
It's closed because the PR is merged but I also pushed it to QA

**Comment by pdpinch** [comment]
@NotoriousMKD would you mind verifying this change to menu on QA, for studio, staging and lms?

**Comment by NotoriousMKD** [comment]
@pdpinch @blarghmatey I see the change on QA except on the 500 pages, which is the first page I hit when I visit any of the QA URLS without specifying a particular course URL. But those 500 pages also have no theme in general.

**Comment by pdpinch** [comment]
Thanks @NotoriousMKD. It sounds like there's a more fundamental issue with those 500 pages. I'll note this on #384.

**Comment by pdpinch** [comment]
@NotoriousMKD @blarghmatey has this been released to production now?

**Comment by blarghmatey** [comment]
Yes, it went out with the unicode fix.
