### ISSUE TITLE
Ficus: 500 error page isn't themed

### ISSUE THREAD

**Issue by NotoriousMKD** [mitodl/salt-ops#384]
I encountered a 500 error page without the MITx theme. This was generated from trying to load a new course from github. 
![7_28 500 error](https://user-images.githubusercontent.com/8322892/28794799-9167b4ca-7605-11e7-91e1-a0e58a107308.png)
https://lms.mitx.mit.edu/sysadmin/courses

**Comment by pdpinch** [comment]
It seems the 500 error page also doesn't pick up the drop-down menu override added in https://github.com/mitodl/salt-ops/issues/383#issuecomment-319734980

**Comment by amir-qayyum-khan** [comment]
@mitodl/devops @pdpinch this issue appears in deployment, 
because things are working fine on my devstack.

<img width="664" alt="screen shot 2017-08-03 at 4 26 45 pm" src="https://user-images.githubusercontent.com/10431250/28919948-257432d2-7869-11e7-8f90-3cad8dbfb9a5.png">

**Comment by NotoriousMKD** [comment]
Maybe I should add that on the QA stack, I see the error page without a theme on the "Page Not Found" and "Studio Servers Encountered an Error" pages on Studio as well as the one I reported above (the 500 error page on LMS and staging). 
![screenshot 2017-08-03 10 13 30](https://user-images.githubusercontent.com/8322892/28926157-fd33084a-7834-11e7-9170-51d28dba1e22.png)
![screenshot 2017-08-03 10 13 43](https://user-images.githubusercontent.com/8322892/28926158-fd345ad8-7834-11e7-8694-04dd938301f1.png)

**Comment by pdpinch** [comment]
@amir-qayyum-khan I'm going to move this back into "Ready" since I don't think you're actively working on this.

**Comment by amir-qayyum-khan** [comment]
ok

**Comment by pdpinch** [comment]
@amir-qayyum-khan still not working. See https://lms.mitx.mit.edu/courses/course-v1:MITx+16.83r_1+2017_Fall/about (from https://github.com/mitodl/mitx-theme/issues/33)

**Comment by shaidar** [comment]
Just to clarify that https://lms.mitx.mit.edu/500 is properly themed, but the course specific one appears not to be

**Comment by pdpinch** [comment]
This has finally been fixed, although I think the 404 error page now isn't themed...
