### ISSUE TITLE
Ficus: student can't submit to python grader after getting 500 Error

### ISSUE THREAD

**Issue by NotoriousMKD** [mitodl/salt-ops#385]
The 6.001 course has had two instances of users seeing a 500 error when trying to submit answers to python grader questions since the upgrade.

- The first student was ayue@mit.edu. 
  - Ana and I both reset his state but he continued to see the error.
  - I'm not getting that error and neither is Ana
  - when I view the problems in the course as his user, I do see that error
  - I don't see it as a generic student. 
  - This student ended up trying in a different browser and was able to submit without any issues but was never able to have success in the original browser, which the screen shot shows was Firefox.

![python error](https://user-images.githubusercontent.com/8322892/28795971-c9e40624-7609-11e7-9856-e0d0fd6e537b.png)
https://lms.mitx.mit.edu/courses/course-v1:MITx+6.0001.ASEr+Exam/courseware/fc8f42302c644118adfcfa720f9f403e/35f82f6c3ecb4e9e913dc279a9b73a9f/

- The second person was her TA oceliker@mit.edu, and he had the same thing happen (500 error when submitting to graders) He:
  - was using Chrome. 
  - did a fresh install of Firefox and it did NOT work.
  - cleared only cache in regular Chrome and it did NOT work. 
  - cleared only cookies in regular Chrome and it DID work.
  - used incognito in Chrome and it DID work.

**Comment by pdpinch** [comment]
This doesn't seem to be an issue anymore? We saw some errors in the 9/18 quiz that were caused by bugs in the grader. This did not, however, block the students from re-submitting. 

We can always re-open the issue if this does occur again.
