### ISSUE TITLE
Ficus: wrong URL in enrollment e-mails

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#386]
When an instructor enrolls a learner, they have an option to have an e-mail sent to the learner. 

Based on ZenDesk issues, it appears that when an e-mail is generated for learners who don't yet have an account, it sends them the wrong URL for registering. For example:

> Dear student,

> You have been invited to join [redacted] at localhost by a member of the course staff.

> To finish your registration, please visit https://localhost/register and fill out the registration form making sure to use [redacted]  in the E-mail field.
> Once you have registered and activated your account, you will see [redacted]  listed on your dashboard.

> ----
> This email was automatically sent from localhost to [redacted]

**Comment by pdpinch** [comment]
Also, since the registration method for MITx residential is different, we'd like to change this template.

**Comment by amir-qayyum-khan** [comment]
so do you want to change all contents of this template, because the url comes from the lms.env.json file

@mitodl/devops

**Comment by blarghmatey** [comment]
@amir-qayyum-khan what value from the file is it using?

**Comment by amir-qayyum-khan** [comment]
@blarghmatey `SITE_NAME`

**Comment by pdpinch** [comment]
We'll look into changing that setting, but it's also used by xqueue. 

In any case, the instructions in this registration e-mail are wrong for our installation. Can we override it? @amir-qayyum-khan where is this template located. I'd like to take a look at editing it.

**Comment by amir-qayyum-khan** [comment]
yes we can easily do that @pdpinch 

https://github.com/mitodl/edx-platform/blob/master/lms/templates/emails/enroll_email_allowedmessage.txt#L21
