### ISSUE TITLE
Set up Salt UI on salt master

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#39]
In order to make the salt master more approachable for non-ops people and start working toward one-button actions for users it is necessary to implement a web UI. The current strongest options are [SaltPad](https://github.com/Lothiraldan/saltpad) and [Molten](https://github.com/martinhoefling/molten), of which SaltPad appears to be the more well engineered option.

**Comment by blarghmatey** [comment]
This is already partially implemented in mitodl/master-formula but will likely need some updating to account for code changes in SaltPad.

**Comment by pdpinch** [comment]
@mitodl/devops what's the status of this?

**Comment by blarghmatey** [comment]
This is a low priority item that we will try to get implemented when we have a brief lull between projects. It is largely complete, but there have been some recent changes to the saltpad code base that will require updates to the formula that is written at the moment.

**Comment by blarghmatey** [comment]
SaltPad is defunct. A currently active project is https://github.com/erwindon/SaltGUI

**Comment by shaidar** [comment]
Appears that SaltGUI is still one of top ones and still actively developed.

**Comment by blarghmatey** [comment]
This looks like a good option with the most comprehensive list of features https://github.com/latenighttales/alcali-formula
