### ISSUE TITLE
Email Invitation to Students via Studio Uses Link to Staging 

### ISSUE THREAD

**Issue by NotoriousMKD** [mitodl/salt-ops#398]
If an instructor uses the studio interface to invite students to enroll in their course, the pre-drafted email is populated with a link to the staging site. 
![screenshot 2017-08-28 12 38 54](https://user-images.githubusercontent.com/8322892/29783327-f6e6a31c-8bed-11e7-850c-70fab08de075.png)
https://studio.mitx.mit.edu/settings/details/MIT/MKD8.011/2017_Summer

It should go to the LMS site.

**Comment by pdpinch** [comment]
@amir-qayyum-khan do you think we can override with this with the theme -- either to change the URL or hide the entire block (on staging)?

**Comment by amir-qayyum-khan** [comment]
@pdpinch we can override it i.e remove it or can point it to lms 

https://github.com/mitodl/edx-platform/blob/master/cms/templates/settings.html#L108

**Comment by amir-qayyum-khan** [comment]
@pdpinch i removed this section from studo

**Comment by pdpinch** [comment]
@mitodl/devops this looks good on QA. Please release this theme update to production whenever we do our next update.

**Comment by pdpinch** [comment]
This was released in October.
