### ISSUE TITLE
CAS: Long URLs get truncated leading to 500 error

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#408]
Our CAS server is running on an older version of django which limits URLField to a small text field with a fixed number of characters. If an MITx link requiring authentication is too long, it leads to a 500 error. 

This most often happens to users who use OWA (Outlook Web Access) which protects URLs in email with a very long redirect URL. 

The current workaround for users who encounter this issue is to copy and paste the URL or to type it out themselves.

**Comment by amir-qayyum-khan** [comment]
which repo @pdpinch ?

**Comment by pdpinch** [comment]
Same as the one where you fixed the encode/decode of ‘+’ 

I’ll look it up when I’m at a computer. 

----------------
I am mobile.

**Comment by pdpinch** [comment]
https://github.mit.edu/mitx-devops/mitx-cas

**Comment by amir-qayyum-khan** [comment]
thanks it is different repo

**Comment by pdpinch** [comment]
I understand from @blarghmatey that we are running into deployment issues with this update.

**Comment by blarghmatey** [comment]
Yes. After pulling in the latest changes the migrations wouldn't apply until I upgraded a number of the other dependecies due to the fact that they required South.

After upgrading the necessary dependencies I was able to apply the migrations but then I started running into errors with processing the response from Shibboleth which will require more debugging and code updates.

**Comment by pdpinch** [comment]
I thought upgrading was the easy way out of this field length restriction. If we should take another tack, let me know.

**Comment by amir-qayyum-khan** [comment]
can you help me setting this on my local machine, so that i can investigate?

**Comment by blarghmatey** [comment]
I think the easiest thing might be to just set the `max_length` argument for the `service` field in django-cas-provider and then generating the corresponding migration.

**Comment by amir-qayyum-khan** [comment]
@blarghmatey do we need to revert my [PR](https://github.com/mitocw/django-cas-provider/pull/5) and then add this `max_length`?

**Comment by blarghmatey** [comment]
@amir-qayyum-khan I did that for the django-cas-provider and applied the change on our QA instance of CAS so we are all set. I'll be deploying it to the production instances today.

**Comment by blarghmatey** [comment]
This has been deployed to the production instances.
