### ISSUE TITLE
CAS: stop decoding plus (+) in URLs

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#409]
Now that we use split mongo in edX, course URLs frequently have plus (+) signs in them. CAS is decoding these plus signs into spaces, leading to 404s when users view a course page and need to authenticate. 

See [ZenDesk #10881](https://odl.zendesk.com/agent/tickets/10881)

An example of the chain of requests:

```
    https://lms/login
    https://lms/cas-auth/login/
    https://cas/login?appname=MITx&service=https%3A%2F%2Flms.mitx.mit.edu%2Fcas-auth%2Flogin%2F%3Fnext%3D%252Fcourses%252Fcourse-v1%253AMITx%252B6.042r_4%252B2017_Fall%252F&provider=touchstone
    [Touchstone stuff]
    https://cas/cas/login?service=https://lms.mitx.mit.edu/cas-auth/login/?next=%2Fcourses%2Fcourse-v1%3AMITx%2B6.042r_4%2B2017_Fall%2F
    https://lms/cas-auth/login/?next=%2Fcourses%2Fcourse-v1%3AMITx+6.042r_4+2017_Fall%2F&ticket=ST-O49DKFwncP8jhbZyiQmJIt2V6SCe1
    https://lms/courses/course-v1:MITx%206.042r_4%202017_Fall/
```

**Comment by amir-qayyum-khan** [comment]
@pdpinch can you give me repo of CAS work?

**Comment by pdpinch** [comment]
https://github.mit.edu/mitx-devops/mitx-cas

I have to make sure you have access

**Comment by amir-qayyum-khan** [comment]
@pdpinch i have access, thanks

**Comment by amir-qayyum-khan** [comment]
@pdpinch the problem appears when `django_cas` encode the **service** param twice.

- https://bitbucket.org/cpcc/django-cas/src/47d19f3a871fa744dabe884758f90fff6ba135d5/django_cas/views.py?at=default&fileviewer=file-view-default#views.py-24
- https://bitbucket.org/cpcc/django-cas/src/47d19f3a871fa744dabe884758f90fff6ba135d5/django_cas/views.py?at=default&fileviewer=file-view-default#views.py-52

#### step to produce:
```python
from urllib import urlencode
from urlparse import urljoin
service = 'https://lms.mitx.mit.edu/cas-auth/login/?'
redirect_to="/courses/course-v1:MITx+6.042r_4+2017_Fall/"
service += urlencode({"next": redirect_to})
print(service)


params = {
'service': service,
'provider': 'touchstone',
'appname': 'MITx'
}

url = urljoin("https://cas/", 'login') + '?' + urlencode(params)
print(url)
``` 

#### Solution is:
Decode element twice, but this can case issue where requestor is not using `django_cas` like [edx-platform](https://github.com/mitodl/edx-platform/blob/master/openedx/core/djangoapps/external_auth/views.py#L473)

**Comment by pdpinch** [comment]
Reopening because we haven't deployed this anywhere yet.

**Comment by pdpinch** [comment]
This has been deployed to Ficus (current release) and Ginkgo (qa-next release).
