### ISSUE TITLE
CAS 500 errors 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#410]
Occasionally, the CAS server will return a 500 error when users try to log in to MITx. When the user gets into this state, in can sometimes help to clear all related cookies, including CAS, Touchstone and the MIT WAYF server. However, it's usually easier for the support team to simply delete the users account in the CAS django admin. This reliably addresses most cases as it ends all CAS sessions. It also deals with a less common error when a user's name changes on their certificate and no longer matches the account in CAS. 

Although we have a reliable workaround, this is still annoying for users and time consuming for support. A permanent solution is desirable, including possibly removing CAS altogether and authenticating MITx with Touchstone Shibboleth directly.  

Notably, this doesn't seem to happen to other services using CAS, like ZenDesk or GitHub Enterprise

**Comment by pdpinch** [comment]
When was the last time we saw this happen?

**Comment by blarghmatey** [comment]
It's been quite a while since I heard of it happening and we are finally using SAML directly so this can be closed.
