### ISSUE TITLE
Set up elastalert for large number of OperationFailure errors

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#439]
Around 5:15pm on 9/29 we saw a rapid increase in `OperationFailure` errors due to a loss of database credentials. We weren't alerted to the issue until we received a large number of ZenDesk tickets, followed by a number of e-mailed stack traces. 

https://logs.odl.mit.edu/goto/b72eb6e5153d8961436766bc476a07dc

In the future, we would like to have errors on this scale fire an elastalert notification which would immediately go to OpsGenie

**Comment by pdpinch** [comment]
@shaidar how much work is this to set up?

**Comment by shaidar** [comment]
I'll work on that today as I need to spend some time working on the ES logging cluster, but should be a simple alert to write.

**Comment by shaidar** [comment]
Submitted [PR#186](https://github.mit.edu/mitx-devops/salt-pillar/pull/186/files)

**Comment by shaidar** [comment]
Merged and deployed
