### ISSUE TITLE
allow re-runs in studio

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#459]
As a (django) staff user, I'd like to be able to re-run a course using the studio re-run function. 

We think this will create fewer issues than exporting and importing a course in order to run it again in another semester.

**Comment by amir-qayyum-khan** [comment]
@pdpinch i am working on this, Do you want me to add rerun functionality on django admin?

**Comment by amir-qayyum-khan** [comment]
@pdpinch i am working on this, Do you want me to add rerun functionality on django admin?

**Comment by amir-qayyum-khan** [comment]
@pdpinch i am working on this, Do you want me to add rerun functionality on django admin?

**Comment by amir-qayyum-khan** [comment]
@pdpinch i am working on this, Do you want me to add rerun functionality on django admin?

**Comment by amir-qayyum-khan** [comment]
@pdpinch i am working on this, Do you want me to add rerun functionality on django admin?

**Comment by amir-qayyum-khan** [comment]
@pdpinch i am working on this, Do you want me to add rerun functionality on django admin?

**Comment by amir-qayyum-khan** [comment]
@pdpinch i am working on this, Do you want me to add rerun functionality on django admin?

**Comment by amir-qayyum-khan** [comment]
@pdpinch is responsible for reruns
`ALLOW_COURSE_RERUNS: true`

it is cms feature flag, part of cms env

**Comment by amir-qayyum-khan** [comment]
@pdpinch is responsible for reruns
`ALLOW_COURSE_RERUNS: true`

it is cms feature flag, part of cms env

**Comment by amir-qayyum-khan** [comment]
@pdpinch is responsible for reruns
`ALLOW_COURSE_RERUNS: true`

it is cms feature flag, part of cms env

**Comment by pdpinch** [comment]
Thanks Amir. I can't find this anywhere in the documentation. If it works, I'll open an issue with edX to fix that.

**Comment by amir-qayyum-khan** [comment]
sure

**Comment by shaidar** [comment]
This change has been made to ansible_vars in pillar data and will be applied to ginkgo release.

**Comment by pdpinch** [comment]
This works. I was able to re-run https://studio-mitx-qa-next.mitx.mit.edu/course/MITx/TEST101/2014_Spring as https://studio-mitx-qa-next.mitx.mit.edu/course/course-v1:TestX+TEST101+2018_Spring
