### ISSUE TITLE
Ficus: Allow instructors to export to remote gradebook in parallel

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#468]
Currently, when an instructor exports the results of a problem to the remote gradebook, they are limited to doing only one export at a time. For some large courses and/or complex problems, it can take up to an hour to generate the grade report for export. It would be very convenient to run multiple of these in parallel. 

I believe the code that queues the grading jobs to celery uses a combination of job type and course id as the key. If a second job with the same key is submitted it will be rejected. A workaround for this case would be to use the problem id instead of the course id in the key. Or maybe in addition to the course id. The trick is making sure the the instructor dashboard can still display updates from the celery queue.

**Comment by pdpinch** [comment]
For now, just take a look and let us know how big a change this would be.

**Comment by amir-qayyum-khan** [comment]
i will drop you an email. because tomorrow is MIT holiday.

**Comment by amir-qayyum-khan** [comment]
@pdpinch solution is very simple
- A unique task is represented by `course_id, task_type, task_key`, please [see](https://github.com/mitodl/edx-platform/blob/mitx/ficus/lms/djangoapps/instructor_task/api_helper.py#L33)
- if i make `task_key` unique for every RGB, and CSV download from remote task. It will solve our problem
- please see solution [here](https://github.com/mitodl/edx-platform/pull/45)

**Comment by pdpinch** [comment]
I confirmed this is functional in production.
