### ISSUE TITLE
Ginkgo: remove register button from root template

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#469]
This is the not-logged-in state: 

<img width="1392" alt="screenshot 2017-11-11 08 40 10" src="https://user-images.githubusercontent.com/430126/32689940-f5f13b9e-c6bb-11e7-961f-a7a9b802bb65.png">

**Comment by pdpinch** [comment]
@annagav can you take this?

**Comment by amir-qayyum-khan** [comment]
You can fix this by setting 
- `RESTRICT_ENROLL_BY_REG_METHOD`: false and `ALLOW_PUBLIC_ACCOUNT_CREATION`: false

Also I made a [PR](https://github.com/mitodl/mitx-theme/pull/36/) to make changes on mitx-theme side.

**Comment by pdpinch** [comment]
I agree that `ALLOW_PUBLIC_ACCOUNT_CREATION` should be set to `false`, but what does `RESTRICT_ENROLL_BY_REG_METHOD` have to do with it? 

Do we need to change the theme *and* the feature flag? Shouldn't the feature flag be enough?

**Comment by amir-qayyum-khan** [comment]
@pdpinch 
- you need to change both flags to achieve this. please see [code](https://github.com/edx/edx-platform/blob/master/lms/templates/navigation/navbar-not-authenticated.html#L36)
- Theme is alternative solution, with my theme changes you dont have to set any flag, it will take care of issue

**Comment by pdpinch** [comment]
the feature flags have been changed, and that is sufficient.
