### ISSUE TITLE
Hawthorn: replace studio favicon

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#470]
<img width="360" alt="screenshot 2017-11-11 08 42 43" src="https://user-images.githubusercontent.com/430126/32689957-5607fa40-c6bc-11e7-98fe-44c662d8ec69.png">

**Comment by pdpinch** [comment]
Are both of these PRs necessary? Why do we have to make a change to edx-platform to make this work?

**Comment by pdpinch** [comment]
We will test this on QA when convenient for @mitodl/devops

**Comment by pdpinch** [comment]
This still isn't working for me on https://studio-mitx-qa.mitx.mit.edu/home/ -- @mitodl/devops has it been deployed?

**Comment by pdpinch** [comment]
This still isn't working, but I don't care any more for Ginkgo. We can consider tackling this again when we do the Summer 2018 update to Hawthorn.

**Comment by shaidar** [comment]
Closing for now
