### ISSUE TITLE
Ginkgo: View Live button on studio-next links to draft server

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#475]
When you attempt to view live  you are directed to the wrong server, which fails with a CAS error. 

<img width="1373" alt="screenshot 2017-11-14 08 29 19" src="https://user-images.githubusercontent.com/430126/32782459-733731f6-c916-11e7-9ab3-5ca54c5d44f7.png">

**Comment by amir-qayyum-khan** [comment]
@mitodl/devops @blarghmatey @shaidar @pdpinch please update these settings in cms.env.json

- PREVIEW_LMS_BASE
- LMS_BASE
- LMS_ROOT_URL
![screen shot 2017-11-20 at 4 59 35 pm](https://user-images.githubusercontent.com/10431250/33017489-5b8eed02-ce14-11e7-88a2-2716baded1bd.png)


![screen shot 2017-11-20 at 4 58 27 pm](https://user-images.githubusercontent.com/10431250/33017488-5b64437c-ce14-11e7-9a66-12475e9f2b74.png)

**Comment by pdpinch** [comment]
I can no longer reproduce this issue. 

I think this was caused by a load-balancer configuration issue that was fixed on Friday.
