### ISSUE TITLE
Ginkgo: "export to git with every course publish event" is not functioning

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#476]
I'm testing with the course at https://studio-mitx-qa-next.mitx.mit.edu/course/course-v1:TestX+AutoExport101+2018_Spring and the repo at https://github.mit.edu/MITx-Studio2LMS/content-textx-autoexport101-2018_Spring

The course's git url is set in advanced settings. When I publish changes in the course, I'm expecting to see them exported to the repo. 

I see updates to the course overview in the logs: https://logs.odl.mit.edu/app/kibana#/doc/logstash-*/logstash-mitx-qa-2017.11.14/fluentd?id=AV-6wmF7dSFSFAP1DCZv&_g=()

And I see course publish events: https://logs.odl.mit.edu/app/kibana#/doc/logstash-*/logstash-mitx-qa-2017.11.14/fluentd?id=AV-6ywKhkBlgpJ2OaRZ9&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-15m,mode:quick,to:now))

But I don't see anything about export. 

And there are no new commits in my repo. Just the one I initiated manual by clicking the "export to git" button.

**Comment by amir-qayyum-khan** [comment]
i think @gsidebo fixed this in #49

**Comment by pdpinch** [comment]
This is working for me on mitx-qa-next, now that https://github.com/mitodl/edx-platform/pull/54 has merged. 

@mitodl/devops can you close this once that commit is part of the AMI build?

**Comment by blarghmatey** [comment]
I'm building a new set of AMIs now so I'm closing this issue.
