### ISSUE TITLE
Ginkgo: turn on IDDE

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#483]
IDDE -- individual due date extensions -- is a popular feature used to change the due date for an individual user. It was working in Ficus. 

If I recall correctly, IDDE requires two feature flags, one to turn on the feature and another to add it to the list of override applications (the other popular one being CCX, something we don't need fo residential. 

related to https://github.mit.edu/mitx/Spring-2018/issues/21

**Comment by pdpinch** [comment]
@blarghmatey is this deployed on mitx-qa-next yet? 

I can successfully change the due date for my user, and can confirm in the staff debug interface. But the courseware page doesn't update. 


<img width="1392" alt="screenshot 2017-11-29 12 13 16" src="https://user-images.githubusercontent.com/430126/33388778-dbb4f6b6-d4fe-11e7-982b-634e91ce0f2c.png">

<img width="1392" alt="screenshot 2017-11-29 12 13 32" src="https://user-images.githubusercontent.com/430126/33388777-dba85082-d4fe-11e7-8b65-72d271078c64.png">

<img width="1392" alt="screenshot 2017-11-29 12 13 50" src="https://user-images.githubusercontent.com/430126/33388776-db962ec0-d4fe-11e7-8669-fdd9f80897d9.png">

**Comment by blarghmatey** [comment]
I had initially added it to the wrong location in pillar. It is in the right place now and should be functioning properly if you want to test again @pdpinch

**Comment by pdpinch** [comment]
I'm persuaded that this is turned on now, and that the behavior above is a regression in Ginkgo. I've opened a separate issue #488 for that.
