### ISSUE TITLE
Ginkgo: Allow instructors to export to remote gradebook in parallel 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#484]
Apply the commit in https://github.com/mitodl/edx-platform/commit/1862e9c68f5bbeef10a0a734c85f56020bc405c0 to our ginkgo branch.

**Comment by shaidar** [comment]
This has been applied to the ginkgo branch and will be available on the next QA build.

**Comment by pdpinch** [comment]
This isn't working for me. The gradebook tasks don't seem to be run in celery. Is 
91b9b84 included in our Ginkgo branch?

**Comment by pdpinch** [comment]
Ok, this is working for me now. Thank you @amir-qayyum-khan and @mitodl/devops
