### ISSUE TITLE
Ginkgo: confirm that "View in Studio" on lms links to studio on the same server

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#487]
In the QA stack, you can test this by navigating to a course block on lms, ([for example](https://mitx-qa-next.mitx.mit.edu/courses/course-v1:MITx+6.0002r_6+2017_Fall/courseware/51fea79ef9074d6b901987a66ea81238/84e4b62385334151b2acce9378265455/?activate_block_id=block-v1%3AMITx%2B6.0002r_6%2B2017_Fall%2Btype%40sequential%2Bblock%4084e4b62385334151b2acce9378265455)) as a staff and click on the "View Unit in Studio" button. You should then navigate to [studio-mitx-qa-next](https://studio-mitx-qa-next.mitx.mit.edu/container/block-v1:MITx+6.0002r_6+2017_Fall+type@vertical+block@4ee332dff5604f569c7566b232b34d40)

In production, this means that Studio links from lms.mitx.mit.edu should go to studio.mitx.mit.edu and that DNS for studio.mitx.mit.edu should point to the same machine as lms.mitx.mit.edu.

**Comment by blarghmatey** [comment]
This is functioning properly in QA but will require a minor update when we release to production. I have opened PRs https://github.mit.edu/mitx-devops/salt-pillar/pull/206 and https://github.com/mitodl/salt-ops/pull/493
