### ISSUE TITLE
Ginkgo: elastalert for git errors

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#489]
Given that git errors are not always visible to our users, I'd like to have them escalated quickly to where we can see them and do something about them. 

Not knowing what the frequency will be, I suggest that we start aggressively and send all events with a `log_level` of `Error` and a `filename` of `git_import.py` or `git_export_utils.py` to a Slack channel (perhaps #mitx-tech, assuming that the ETs may be able to address these as quickly as Engineering). 

And then if there is a more than 5 of them in an hour we should send an alert to OpsGenie.

**Comment by shaidar** [comment]
[PR#08](https://github.mit.edu/mitx-devops/salt-pillar/pull/208)

**Comment by pdpinch** [comment]
@blarghmatey it looks like https://github.mit.edu/mitx-devops/salt-pillar/pull/208/files covers both cases I asked for: `git_import.py` or `git_export_utils.py`

**Comment by pdpinch** [comment]
@shaidar can we close this?
