### ISSUE TITLE
Hawthorn: Collaborator accounts shouldn't require activation

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#506]
In fact, no new accounts should require activation. 

<img width="1363" alt="screenshot 2017-12-21 16 10 18" src="https://github.mit.edu/storage/user/10/files/878aa8b6-e669-11e7-9b3a-7aec01e34169">

**Comment by pdpinch** [comment]
Do we have `BYPASS_ACTIVATION_EMAIL_FOR_EXTAUTH` set to true?

See https://openedx.slack.com/archives/C08B4LZEZ/p1513895883000077?thread_ts=1513892162.000213&cid=C08B4LZEZ

**Comment by shaidar** [comment]
Yes, we have this flag set to true

**Comment by pdpinch** [comment]
I'm having trouble reproducing this. I'll assign it to myself, to reproduce or close.
