### ISSUE TITLE
Hawthorn: missing 503 error page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#511]
I'm not sure if this is a theme issue, or what. But when there's a 503 error, the response is empty.

**Comment by pdpinch** [comment]
@gsidebo do you think this is addressed by https://github.com/mitodl/edx-platform/pull/67 ?

**Comment by gsidebo** [comment]
I'd say most likely not. I'm pretty sure my fix works for 404s and 500s, not 503s. I don't think we even have a custom error page for 503s. I would need some way to reproduce this in order to say for sure

**Comment by pdpinch** [comment]
We can live with this for now, but I'd like to make another attempt for Hawthorn.

**Comment by pdpinch** [comment]
Depending on the nature of the 503 error, it may originate in the load balancer. In that case, edX doesn't even have a chance to provide an error page. 

Unfortunately, it my experience the load balancer returns an empty page (with a 503 header) under these circumstances. It's difficult for a naive user to know what to do.

**Comment by pdpinch** [comment]
People have been asking for Amazon a customizable 503 message (or any message) since 2011. 

https://forums.aws.amazon.com/thread.jspa?threadID=72363&start=100&tstart=0

Instead of customizing the message, can we get monit to set an urgent alert if any of the QA or production stacks are returning 503?

**Comment by blarghmatey** [comment]
@shaidar can you add a check for Monit to run against our LMS instances to alert on 503 errors. Probably deploy the agent with those checks to something in the ops VPC

**Comment by shaidar** [comment]
Added a [PR](https://github.com/mitodl/salt-ops/pull/626/files) to post message to slack when 503 encountered

**Comment by blarghmatey** [comment]
We may finally have an answer for this https://aws.amazon.com/about-aws/whats-new/2018/07/elastic-load-balancing-announces-support-for-redirects-and-fixed-responses-for-application-load-balancer/
