### ISSUE TITLE
Build or fork formula for installing and managing Monit

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#524]
[Monit](https://mmonit.com/monit/) is a utility for ensuring that processes and/or external network services are running and in a healthy state. We would like to start leveraging it to ensure that our systems are running and able to communicate with each other. To handle deploying it on our infrastructure we can either use the formula found at https://github.com/saltstack-formulas/monit-formula directly or as inspiration for our own formula.

**Comment by pdpinch** [comment]
Can this be closed?
