### ISSUE TITLE
Configure Monit to raise alerts to the proper channels

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#525]
Define an escalation path for Monit to allow it to raise alerts to any/all of Slack, OpsGenie, Email to ensure proper visibility of system issues based on the perceived severity of the event.

**Comment by pdpinch** [comment]
Is this done?

**Comment by shaidar** [comment]
The salt formula is written and am focused on getting the various alerts in [issue#526](https://github.com/mitodl/salt-ops/issues/526) written. Think initially the plan is to get all the alerts going into a designated slack channel and the tweaking some of them based on noise and usefulness.

**Comment by shaidar** [comment]
Alerts are published to a slack channel from residential instances.
