### ISSUE TITLE
Configure Monit to track system connectivity and uptime

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#526]
Things to manage as the initial priorities once we get Monit deployed:
- edX app connectivity:
  - Mongo
  - MySQL
  - RabbitMQ
- latex2edx availability
- SSL certificate lifetimes:
  - micromasters
  - lms.mitx.mit.edu
  - starcellbio
  - CAS servers
  - OVS
  - OCW
  - lmodproxy

**Comment by shaidar** [comment]
I have completed writing the following alerts:
- mysql
- mongo: proved a bit challenging as the documentation was not very clear but I ended up finding out through the mailing list that monit currently has no ability to do an authenticated check to mongodb and all it can do is an anonymous check and verify that the host is up
- latex2edx
- SSL certificate lifetimes:
  - lms.mitx.mit.edu
  - OVS
  - CAS servers
  - lmodproxy: this was a bit of rabbit hole as it's running in a container and I ended up submitting a [PR](https://github.com/mitodl/lmod_proxy/pull/57) to publish a status which we can then have monit read and alert based off of that.

**Comment by shaidar** [comment]
Monit and associated alerts have been deployed to prod residential instances except for the lmodproxy app cert alert as that requires a new deployment of lmodproxy app that publishes new status endpoint.
