### ISSUE TITLE
Hawthorn: Test Automatic enrollment after registration

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#541]
When an instructor enrolls a student who is not yet registered, the student cannot be enrolled -- because they don't have a user account. A record is created in the `enrollments_allowed` table and when the account is created, it is supposed to be automatically enrolled in the course.

This isn't working in Ginkgo. Actually, I think it stopped working in Ficus. It's confusing to students because they get an e-mail inviting them to a course, but after they register (automatically, via Touchstone) the course does not appear on their dashboard. (Maybe we could mitigate this by including the URL of the course in the initial e-mail?). 

See https://odl.zendesk.com/agent/tickets/13969

### acceptance criteria:
- [ ] is this still an issue in Hawthorn? (test in devstack and then on -next stack)

**Comment by pdpinch** [comment]
We might be able to test this with the new MITx Ginkgo devstack. However, I suspect that this is affected by our use of CAS in production which isn't enabled in the devstack.

**Comment by pdpinch** [comment]
Assigning to myself to do some more investigation

**Comment by pdpinch** [comment]
I don't think we're going to fix this in Ginkgo. We'll have to test it in Hawthorn.

**Comment by annagav** [comment]
@pdpinch is batch enrollment under the membership tab the only way to enroll students?

**Comment by annagav** [comment]
This worked for me on devstack. I enrolled my student, then registered as a student and the course was on my dashboard.  Now waiting to get staff/instructor account to test this on `mitx-qa-next`.

**Comment by annagav** [comment]
So successfully invited Max to the course, he got the email and he was enrolled in the course. But I think he was already registered, given the message and the email he got:

![screen shot 2018-06-13 at 10 12 18 am](https://user-images.githubusercontent.com/7574259/41356553-267060ea-6ef2-11e8-8fe7-fafb54ccb798.png)

**Comment by pdpinch** [comment]
Yeah, in my experience that message means that he already has an account. 

@mitodl/devops can we give Anna admin access on qa-next so she can look up who already has an account? Maybe @NotoriousMKD can suggest an MITx person who doesn't have one yet who can help testing. I would suggest Elaine or Rob, but they are both out sick today. Maybe Matt?

**Comment by pdpinch** [comment]
Also, there's [this ticket](https://github.mit.edu/mitx/Summer-2018/issues/27) which just came in.

**Comment by annagav** [comment]
I invited Matt to a course on `mitx-qa-next` he received the email invitation with the link to the course where he can finish the enrollment by clicking the enroll button. But he was not automatically enrolled. Checked `Course enrollment alloweds` for all my test users `auto_enroll` is set to `True`.

I tested this locally on `mitx/hawthorn` branch, and auto enrollment worked.

**Comment by pdpinch** [comment]
Uh, what are we going to do about this?

**Comment by blarghmatey** [comment]
This will be closed by https://github.com/mitodl/edx-platform/pull/97
