### ISSUE TITLE
MITx devstack: create standard staff, honor and verified users 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#542]
In edX's devstack there are (at least?) three standard user accounts set up: staff@example.com, honor@example.com and verified@example.com. See http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/installation/installation_options.html for details.

We should set up the same accounts in the MITx devstack so we can leverage edX's documentation and the team's general familiarity. 

See https://github.com/mitodl/salt-ops/blob/master/salt/edx/django_user.sls#L1

**Comment by shaidar** [comment]
[PR#543](https://github.com/mitodl/salt-ops/pull/543 should address this and once it's merged I'll run another devstack build and upload to S3
