### ISSUE TITLE
RGB tasks: Progress reset in code result task state incomplete

### ISSUE THREAD

**Issue by amir-qayyum-khan** [mitodl/salt-ops#549]
Due to progress success variable reset in our code, we see task state incomplete on RGB dashboard.

- We iterate over all student grades one by one and count progress, For example if students are 540
this part of [code](https://github.com/mitodl/edx-platform/blob/mitx/ginkgo/lms/djangoapps/instructor/views/instructor_task_helpers.py#L186) will set it to 540 success which will result task sate complete 

- But there is a redundant [code](https://github.com/mitodl/edx-platform/blob/mitx/ginkgo/lms/djangoapps/instructor_task/tasks_helper/misc.py#L369) that is resetting this value calculate above which is casing task state incomplete, but the task ran correctly the issue is in task progress counter.

@pdpinch 

### TO FIX
**remove these lines**
- https://github.com/mitodl/edx-platform/blob/mitx/ginkgo/lms/djangoapps/instructor_task/tasks_helper/misc.py#L367
- https://github.com/mitodl/edx-platform/blob/mitx/ginkgo/lms/djangoapps/instructor_task/tasks_helper/misc.py#L369

![pasted image at 2018_02_23 03_31 pm](https://user-images.githubusercontent.com/10431250/36673909-4367e3d2-1b26-11e8-9f67-3715f2d56b47.png)

**Comment by pdpinch** [comment]
@amir-qayyum-khan I'm testing this on the QA server and it's better but still strange. 

Here's the task output: 

```
{"preassigned": 0, "failed": 0, "step": "Posted to RGB", "skipped": -244, "succeeded": 245, "duration_ms": 3645812, "attempted": 245, "total": 1, "action_name": "export_grades_to_rgb"}
```

And a screenshot 

<img width="1392" alt="screenshot 2018-03-06 10 40 30" src="https://user-images.githubusercontent.com/430126/37041895-42d5bd9e-212b-11e8-82f3-7da1545b762d.png">

"245 recipients" sounds correct. But why is it "out of 1" ?

**Comment by amir-qayyum-khan** [comment]
it seems total is not set in code `"total": 1, `

**Comment by pdpinch** [comment]
This is done except for the "out of 1" issue with the value of the total. I'm going to move it to the backlog for now.

**Comment by amir-qayyum-khan** [comment]
i fixed it here, lets see if we are able to merge it https://github.com/edx/edx-platform/pull/17623

**Comment by pdpinch** [comment]
A fix to this issue was incorporated into the branch https://github.com/mitodl/edx-platform/tree/rgb_upstream_aq
