### ISSUE TITLE
ENABLE_UNICODE_USERNAME set to True on QA but not in production?

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#550]
I noticed this while looking up the feature flag for https://github.com/mitodl/edx-platform/issues/76

ENABLE_UNICODE_USERNAME is set in mitx-qa.sls:

https://github.com/mitodl/salt-ops/blob/master/pillar/edx/mitx-qa.sls#L23

but I don't see how it's set in production. It's not in https://github.com/mitodl/salt-ops/blob/master/pillar/edx/mitx-production.sls or in https://github.com/mitodl/salt-ops/blob/master/pillar/edx/ansible_vars.sls

**Comment by blarghmatey** [comment]
Addressed by #552
