### ISSUE TITLE
Hawthorn: hide registration page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#562]
I just stumbled onto the registration page. I'm not sure if this is a regression in feature flags, or just a page redirect we missed. 

### steps to reproduce

1. Log out of LMS
2. Navigate to a course /about page, such as https://lms.mitx.mit.edu/courses/course-v1:MITx+5.111r_8+2018_Spring/about
3. Click on the Enroll button

### expected behavior

- browser is redirected to Touchstone to start authentication flow

### actual behavior

- browser goes to logistration page, https://lms.mitx.mit.edu/register?course_id=course-v1%3AMITx%2B5.111r_8%2B2018_Spring&enrollment_action=enroll

**Comment by pdpinch** [comment]
Interestingly, if I am signed in and I navigate to https://lms.mitx.mit.edu/register%3Fcourse_id%3Dcourse-v1:MITx%2B5.111r_8%2B2018_Spring I get a 404.

**Comment by pdpinch** [comment]
@amir-qayyum-khan does your PR mean that there isn't a feature flag or theme change that can achieve this?

**Comment by amir-qayyum-khan** [comment]
@pdpinch Yes there is a possible solution via theme https://github.com/mitodl/mitx-theme/pull/81

**Comment by pdpinch** [comment]
@mitodl/devops has https://github.com/mitodl/mitx-theme/commit/81c33245a944246521c993afa848d5f9529a4e4f been deployed?

When I go to https://mitx-qa-next.mitx.mit.edu/register?course_id=course-v1%3ADevOps%2B0.001_2%2Bcourse&enrollment_action=enroll I get redirected to https://mitx-qa-next.mitx.mit.edu/register -- I'm not sure if this is the same wrong behavior or a new wrong behavior.

**Comment by blarghmatey** [comment]
@pdpinch yes it has. The currently deployed revision is `caa25d3d7405920b8201187a9a5e28ea2bb5a559`

**Comment by amir-qayyum-khan** [comment]
register link is there. The PR only fixes navigation from about page button.

**Comment by pdpinch** [comment]
@mitodl/devops which do you prefer, setting up a redirect in the nginx layer, or overriding the template for /register ?

**Comment by pdpinch** [comment]
closed via #631
