### ISSUE TITLE
Hawthorn: cherry-picks

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#582]
With the Hawthorn release, we need to cherry-pick a number of commits that have not been merged into master. 

DRAFT list:
- [x] enroll no at sign
- [x] remote grade book
- [x] auto-export to git
- [x] git logs fix
- [x] IDDE fix
- [x] various fixes to usernames with @ signs
- [ ] Rapid Response XBlock

**Comment by pdpinch** [comment]
List of commits to cherry pick are at https://docs.google.com/spreadsheets/d/1RFJo2bEmYIgQMw5dk8hkHB8d8pWy8l5VuKScP3wS2yE/edit#gid=0

- [ ] There a couple that I'm not sure if we need. 
- [ ] We need to do some cleanup on the remote grade book PR (notably, adding a commit that came later)
- [ ] We should combine the 4 commits related to git export into one
- [ ] We need a commit with the current pinned version of SGA

**Comment by pdpinch** [comment]
I'll open issues for the the boxes above, so we can close this when the other cherry-picks are made.

**Comment by blarghmatey** [comment]
For the SGA and rapid response requirements we actually don't need to commit those to the edx-platform repository as the latest iteration of the configuration repo allows for specifying dependencies as ansible vars so the last two line items can be removed and managed in Salt.

**Comment by pdpinch** [comment]
Does that configuration option work in such a way that:

- [ ] We can override the existing SGA dependency? edX master specifies an older version of SGA. 
- [ ] RapidResponse needs the Aside XBlock *but also* requires some changes to edX platform and, I think, the XBlock library.

**Comment by pdpinch** [comment]
@blarghmatey what's left to do on this issue?
