### ISSUE TITLE
Docker MITx Devstack with custom commits

### ISSUE THREAD

**Issue by jolyonb** [mitodl/salt-ops#595]
This is a list of updates to the VM that would be good to get working.

- [ ] Fix permissions for rabbit - add admin, /celery vhost, etc
- [ ] Ensure that answer submissions can be graded in problems
- [ ] Figure out how to get things running without rsync
- [ ] Reduce number of LMS and CMS gunicorn workers to reduce memory load
- [ ] Turn off forums, elasticsearch, ORA2 etc services
- [ ] Suppress Django warnings regarding obsolescence on course import
- [ ] Update to Hawthorn???

**Comment by shaidar** [comment]
@blarghmatey Is that something we should be looking at now in terms of docker given that that's the supported platform as opposed to vagrant instances?

**Comment by blarghmatey** [comment]
Yeah, if we're going to build an MITx version of devstack then it would probably be done with the docker setup rather than trying to continue supporting Vagrant.

**Comment by shaidar** [comment]
Devs are using the OpenedX devstack and this can be closed now.
