### ISSUE TITLE
Ironwood: Use Shibboleth auth to integrate directly with Touchstone

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#610]
The CAS server has been causing us a number of problems ( #408 #409 #410 ), in addition to needing an OS and django upgrade. Since we don't use CAS to authenticate any services besides Touchstone with edX, it would be simpler to integrate directly with Touchstone via Shibboleth instead. 

We should be able to use the (relatively new) 3rd party auth functionality in edX.

**Comment by blarghmatey** [comment]
We are being forced to push this back another release. SAML login is functional but as part of that we have to expose public account creation with no way to restrict the available authentication mechanisms. We will need to address that shortcoming before the next release.

**Comment by blarghmatey** [comment]
This is now functional in QA next, along with restricting authentication and registration via the API/registration form. We are moving forward with releasing to production during the next maintenance window.
