### ISSUE TITLE
OCW AWS Migration

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#655]
In order to allow for ongoing maintenance and improvement of the OCW application we need to finalize the migration off of the physical hardware and onto AWS infrastructure.

**Comment by blarghmatey** [comment]
I think we can close this epic as the cutover has happened. The mirror is still an open issue, but the bulk of this work is now done.

**Comment by markbreedlove** [comment]
I agree. It's technically been migrated.
