### ISSUE TITLE
disposition of regular OCW tasks

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#657]
Sapient gave us a copy of their [daily, weekly and monthly tasks](https://docs.google.com/spreadsheets/d/1Viy7xuPgkyUtYdR-rhUQdC-r-JEv471BWp_xts7TIZA/edit?usp=sharing). We should review this and decide, for each task: 

- we can stop doing it
- we can automate it 
- we will continue doing it manually 
- or some combination of the above

Any work that needs to be done can be added as an issue on this epic.

**Comment by pdpinch** [comment]
@shaidar besides the retirement engine and the log rotating, are there any other issues in here that need to be addressed?

**Comment by shaidar** [comment]
@pdpinch There's the typical memory, disk, CPU checks that we should be able to perform now with the beats agent. There are also checks to ensure that backups are taking place and eventually that zeopack is working as well. There's also updating/adding `AF Tags` which is also outlined in the routine activity doc.

**Comment by pdpinch** [comment]
@blarghmatey should we close this?

**Comment by pdpinch** [comment]
FYI, Joe is going to run the retirement engine as needed, so that can be removed from the periodic task list.

**Comment by pdpinch** [comment]
And we've shown that the monitoring for disk space issues works, although it took us a few hours to figure out what to do about it. 

I'm going to close this.
