### ISSUE TITLE
OCW: Quiet useless cron alerts

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#700]
The OCW prod team is getting multiple daily alerts from cron on ocwcms and ocwqa. They don't know what to do with them. 

- [ ] update the email address for cron alerts to something more useful
- [ ] quiet any alerts that can be monitored better elsewhere (e.g. [warnings about blob storage size](https://odl.zendesk.com/agent/tickets/22156))

**Comment by shaidar** [comment]
Changed cron jobs on `cms1` to email `odl-devops` for now. Until we move the instances to AWS, think that's a good short term solution

**Comment by pdpinch** [comment]
I'm going to call this done. You can decide for yourselves how annoying the alerts are.
