### ISSUE TITLE
AWS Resource Tagging

### ISSUE THREAD

**Issue by shaidar** [mitodl/salt-ops#709]
In the interest of billing and accurate cost analysis, we should tag all the AWS resources similar to how we have EC2 instances and a few other resources appropriately tagged.

**Comment by blarghmatey** [comment]
As part of this we need to consolidate all OCW related tags to be one value.

**Comment by markbreedlove** [comment]
Are there particular tag keys that we want to focus on?

**Comment by shaidar** [comment]
I believe everything has been tagged except for:
- AMI
- Snapshots
- EBS Volumes

**Comment by markbreedlove** [comment]
I don't recall if all of the AMIs are tagged, but I think snapshots and EBS volumes were tagged sufficiently well, or as well as can be.

**Comment by markbreedlove** [comment]
Regarding AMIs:

The only tags that we use are `Environment`, `Name`, and `org`. Should there be others?

There are hundreds of AMIs owned by us that don't have `Environment`. Some of these are as old as 2013. There are 133 that are more than a year old.

Most of these old AMIs appear to be edX app base images. Are the base images OK to delete?

Most of the old AMIs from the 2013-2014 era seem to be backups. I would need some guidance about tagging or deleting them. Can someone have a look? Many of them start with `mitx-`.

**Comment by markbreedlove** [comment]
BTW, the "name" tag is only used for 2 instances and seems like something we can ignore.

**Comment by markbreedlove** [comment]
`Environment` only has one value, `ttvmit`, and is only used by 8 AMIs.

**Comment by blarghmatey** [comment]
As far as tags to use, the most important are OU and Department. We can definitely delete old AMIs for edx base images, keeping probably the most recent six or dozen. We can likely delete the old AMIs but that will require some digging and can be skipped for now.

**Comment by markbreedlove** [comment]
OK, thanks! I'll delete old edX base images now and fill in OU and Department.

**Comment by markbreedlove** [comment]
AMI tags are now filled in as well as they can be.

**Comment by markbreedlove** [comment]
I think that snapshots are tagged as well as they can be now. Most snapshots are Ike's and are untagged. Most of the rest are OCW snapshots, and the Snapshot Lifecycle policies that create them copy tags over from the volumes, which are tagged thoroughly.

**Comment by markbreedlove** [comment]
Anyone not in favor of closing this issue now?

**Comment by blarghmatey** [comment]
We can open a new one if there is more tagging that needs to be done.
