### ISSUE TITLE
refactor remote gradebook into a pluggable app...

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#714]
... instead of merging code into edx-platform

The remote gradebook export feature is defined by https://github.com/edx/edx-platform/pull/17623 which edX is not going to merge. If possible, we would like to refactor it as a pluggable django app. 

In its current design the app needs to:
- [ ] access some site settings (remote gradebook URL)
- [ ] access some course settings (remote gradebook id
- [ ] add a tab to the instructor dashboard
- [ ] submit jobs to the edx queue
- [ ] access a grades API
- [ ] add output to the instructor dashboard
- [ ] post the results to an external service

**Comment by pdpinch** [comment]
Before working on this, we should check to see if edX has made any progress on external gradebook integrations as part of the masters project.

**Comment by shaidar** [comment]
@pdpinch Is this something we're still interested in doing?

**Comment by pdpinch** [comment]
I’m not sure if the remote grade book is still relevant, after the shift to Canvas. I’ll check. 

To the extent that the Canvas integration may depend on this code, we should still pursue turning it into a pluggable app, to avoid the burden of cherry picks every time we upgrade. 

We should try to answer these questions before we start the Lilac upgrade.
