### ISSUE TITLE
MathJax rendering issue.

### ISSUE THREAD

**Issue by itsbenweeks** [mitodl/salt-ops#72]

**Comment by itsbenweeks** [comment]
See https://github.com/edx/edx-platform/pull/11648, https://github.com/edx/edx-platform/pull/11587, and https://openedx.atlassian.net/browse/TNL-4145 for more info about why and what commits are necessary.

**Comment by pdpinch** [comment]
See also: https://odl.zendesk.com/agent/tickets/2995

https://github.com/edx/edx-platform/commit/e57487db833c237f3baba1b7276852127d44fb53
https://github.com/edx/edx-platform/commit/aa8e4208b74705226efd30ca8651ee706442181b
https://github.com/edx/edx-platform/commit/c63dcf0dfe7e79781fa4b0f83db63e74d51c519c

(I don't think we need to other two commits in edx/edx-platform#11648)

**Comment by blarghmatey** [comment]
Cherrypicked in mitodl/edx-platform#1

**Comment by itsbenweeks** [comment]
This looks good to me now.
