### ISSUE TITLE
Run OCWCMS with Python 2.7

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#721]
Many of the web APIs that OCWCMS integrates with require TLS 1.0 or higher for encryption. Python 2.4 does not support 

If we can run Plone with Python 2.7, we will be able to use a modern version of the openssl library which supports TLS.

**Comment by pdpinch** [comment]
@blarghmatey can you add a comment about why we had to abandon this and close it?

**Comment by blarghmatey** [comment]
After a few days of trial and error I managed to get the buildout script to execute and install the necessary dependencies under Python 2.7. However, upon trying to start the service there were a number of syntax errors in Zope that would have required significant effort to resolve, including having a function definition that contained a keyword argument of `with` which is a reserved word in Python 2.7.

We are abandoning this line of effort and will instead set up a proxy to upgrade HTTP requests from Plone to outgoing HTTPS requests to the external services that we are interfacing with (e.g. 3Play)
