### ISSUE TITLE
Populate OCW QADB with Production DB data 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#732]
Now that we've cleaned the corrupt data from the OCW production CMS, we should update the data on QADB?

I think there's a runbook for this.

**Comment by shaidar** [comment]
By building QA in AWS, it might be best to simply focus on that environment and work on retiring the one hosted by IS&T. @pdpinch @blarghmatey Thoughts?

**Comment by shaidar** [comment]
This is being handled via [Issue#671](https://github.com/mitodl/salt-ops/issues/671)
