### ISSUE TITLE
(process:15153): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#734]
On ocwpcmsdb2 (only?) this message is getting sent to the root user every five minutes, from the cron job

`Cron <munin@ocwpcmsdb2> test -x /usr/bin/munin-cron && /usr/bin/munin-cron`

**Comment by blarghmatey** [comment]
The command doesn't seem to be doing anything so I removed the task since it is generating a huge amount of noise.
