### ISSUE TITLE
Fix bug in CSRF token for registration page on xpro QA environment

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#753]

**Comment by pdpinch** [comment]
@mitodl/devops what have you already tried on this issue?

**Comment by shaidar** [comment]
This turned out to be a redirect rule in the Nginx config. We just need to find out where in the code this is coming from and make the necessary change.

**Comment by markbreedlove** [comment]
@blarghmatey @shaidar Could I get the details on the issue, when you have a second? What was the redirect? I'm noting a few places in the `edx/configuration` Nginx templates where redirects are done. Any chance it's a wrong `$host` value [here](https://github.com/edx/configuration/blob/1482aa3a513fdc6fef7448319c7a6e8b23a2cbb3/playbooks/roles/edx_django_service/templates/edx/app/nginx/sites-available/app.j2#L14)?

**Comment by shaidar** [comment]
@markbreedlove If u take a look at `/etc/nginx/sites-enabled/lms` on one of the xpro lms instances (ex. `edx-mitxpro-qa-xpro-qa-0-v1`), it has the redirect for the `/register` page

**Comment by markbreedlove** [comment]
Had a conversation with @shaidar. He thinks it probably just needs a conditional around the redirect to have it redirect to the login page only if the product is xPro.  See PR #774.
