### ISSUE TITLE
MITxPro: enable automated export to git

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#756]
I think it would behoove us to enable automatic export to git and set up courses the use it. I think having versioning for courseware would benefit the xPro team.

**Comment by pdpinch** [comment]
@mitodl/devops did this code get deployed?

**Comment by shaidar** [comment]
Deployed to RC. Needs testing

**Comment by shaidar** [comment]
@pdpinch This is deployed on RC, but need some info as far as repo/user that will be used for xPro courses.

**Comment by shaidar** [comment]
Deployed to production as part of a new build. Once functionality is confirmed (when repo is created) this can be closed

**Comment by pdpinch** [comment]
Thanks Sar. If I recall correctly, the repo is configured per course, using an advanced setting in the course. 

I think the user needs to be specially configured. Do you think we could reuse the user we have for residential MITx?

**Comment by shaidar** [comment]
I'm closing this now as I believe it's done. If not, please fell free to re-open
