### ISSUE TITLE
Static assets for courses not rendering on LMS/live.

### ISSUE THREAD

**Issue by itsbenweeks** [mitodl/salt-ops#76]
I believe that there are some difference in the file storage between lms/live and draft/staging. Courses' static assets aren't rendering on live.

**Comment by blarghmatey** [comment]
@itsbenweeks This should be all set now. Let me know if you continue to see issues with static assets.

**Comment by itsbenweeks** [comment]
I'm still having issues with static assets on LMS.

**Comment by itsbenweeks** [comment]
@blarghmatey https://dogwood-qa-live.mitx.mit.edu/courses/MITx/2.75r_3/2016_Summer/courseware/Topic_9_Structural_Connections_Interfaces/Kinematic_Couplings/ is a good place to look at static asses. That course is just full of them.

**Comment by itsbenweeks** [comment]
Also worth noting that this is an issue on -draft as well, but only for imported courses. See https://dogwood-qa-draft.mitx.mit.edu/courses/MITx/18.01r_4/2016_Summer/courseware/week1/diff_2-sequential/19 at the bottom there are two missing images.

-live has all imported courses, so I think it is the same issue.

**Comment by itsbenweeks** [comment]
It looks like these are now rendering on `-draft` and `-live`.
