### ISSUE TITLE
Upgrade Elasticsearch logging cluster to 6.x release

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#761]
We are currently running on the 5.x release of the Elastic Stack and we would like to upgrade to the latest release in the 6.x series. This includes:

- [x] reformatting our Pillar data to match the structure defined by the new elastic-stack-formula
- [x] upgrading/redeploying our Kibana instance
- [x] Migrate Kibana Nginx configuration to use the nginx formula
- [x] Distribute the logging cluster across availability zones (it is currently a 5 node cluster all in one AZ)

**Comment by markbreedlove** [comment]
The cluster has a large number of closed indices. For example, `logstash-heroku-2017.12.19`. It's not directly related to the upgrade (though maybe if mapping syntax has changed?) Do you think we should drop them to free up space in the process and to reduce complexity?

**Comment by blarghmatey** [comment]
It doesn't hurt, but it's not critical. In the end, those instances will be terminated anyway so the disk space issue isn't directly relevant here. (I'm assuming that the closed instances aren't included in the replication)

**Comment by markbreedlove** [comment]
@blarghmatey It's my understanding that I'll need to create a new pillar for `logging.sls` under `elastic_stack`.  I assume I'll base it on the one in `elasticsearch`. I'm noticing that  https://github.com/mitodl/salt-ops/blob/master/pillar/elasticsearch/logging.sls#L56 matches the EC2 `tag:role` == `elasticsearch`. Is that going to be an issue if there are other ES clusters with that `role` tag (micromasters, MITx, etc)?

**Comment by markbreedlove** [comment]
@blarghmatey Also in the existing `logging.sls` (https://github.com/mitodl/salt-ops/blob/master/pillar/elasticsearch/logging.sls#L49) the top-level property `elasticsearch` exists, but I'm noticing that https://github.com/mitodl/elastic-stack-formula/blob/28652485540ab89f145188ebd4744f71a1236fcd/elastic-stack/elasticsearch/map.jinja#L34 references `elastic_stack:elasticsearch`. Am I correct to assume I should nest `elasticsearch` under `elastic_stack`?

**Comment by markbreedlove** [comment]
@blarghmatey updated https://github.com/mitodl/salt-ops/issues/761#issuecomment-473357636 regarding cluster naming.

**Comment by blarghmatey** [comment]
At face value I think that's fine, but I don't think it's necessary. As long as we're staying up to date with the versions it's possible to just do rolling upgrades, so there shouldn't be a need to build a whole new cluster in parallel in the future. Also, that tag gets set as part of the orchestrate routine based on the environment name that is passed in https://github.com/mitodl/salt-ops/blob/master/salt/orchestrate/services/elasticsearch.sls#L39

**Comment by markbreedlove** [comment]
@blarghmatey Do you think that I should add `salt/orchestrate/operations/services/elastic_stack.sls` to the project? Or use individual `.sls` files for the separate services? There's one there now for Kibana, but not for the other services.

**Comment by blarghmatey** [comment]
There is an orchestrate script for elasticsearch at `salt/orchestrate/services/elasticsearch.sls` which is designed to be agnostic to environments and which we should use for this deployment. There is also an orchestrate script at `salt/orchestrate/apps/deploy.sls' which should work for setting up the Kibana host.

**Comment by markbreedlove** [comment]
Right, thanks, finally seeing that now! It looks like it loops through available subnets to assign the new nodes across subnets (and AZs).

**Comment by blarghmatey** [comment]
Correct :+1:

**Comment by markbreedlove** [comment]
Currently migrating data.
