### ISSUE TITLE
Move Zope database to EBS volume

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#762]
The current deployment is using an EFS mount for storing the ZODB file. In order to improve performance and simplify snapshots/backups we would like to move it to an EBS volume. Once this is complete, we want to implement a scheduled run of the Repozo tool for incremental backups.

**Comment by markbreedlove** [comment]
Per discussion with @blarghmatey today, there are a couple of pieces to this.

First, I'll probably just be adding an EBS volume and setting tags on it manually. After that comes the potential addition of a state file to [`salt/orchestrate/services`](https://github.com/mitodl/salt-ops/tree/de4b3a15a041f0ddf09bf20bd1b553cf504b3589/salt/orchestrate/services) to provision the resources in the future (I suppose if the environment ever has to be duplicated or recreated).

The latter part might not be necessary right now, but I could add it to document what's been added by hand.

Tobias thought @shaidar might have a sense of how big to size the new EBS volume. It seems that the existing data take about 60 GiB -- at least the portion that we want. Would something like 5x this amount -- 300 GiB -- be about right, to allow for growth?

There are backup files on the EFS volume that I assume can stay there, and they take up most of the used space.

**Comment by markbreedlove** [comment]
current status: copying files between volumes, waiting for rsync ...

**Comment by markbreedlove** [comment]
The file transfer is done. I can make another pass with `rsync` when it's time to switch to the new volume, to catch updated files. We have a 300 GiB volume with 41% used -- 113GiB. The directories transferred were those that were symlinked to underneath `/usr/local/Plone/zeocluster/var`:
* `/mnt/zeo/blob/blobstorage`
* `/mnt/zeo/cat/catalogstorage`
* `/mnt/zeo/blob/filestorage`
(Those are the old locations.) I'll put more information in Slack ...
