### ISSUE TITLE
Hawthorn hot fix: update help link 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#769]
Somehow the help link got broken in the hawthorn theme. Since we have to change it anyway, it would be best to point it to https://odl.zendesk.com/hc/en-us/requests/new -- which only works for non-agents in ZenDesk.

**Comment by pdpinch** [comment]
@NotoriousMKD says that, for staff/instructors, the help link goes to https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/open-release-hawthorn.master/CA_instructor_dash_help.html -- which seems appropriate. 

For students, it could go to https://odl.zendesk.com/hc/en-us/requests/new -- which doesn't work for ZenDesk agents. But for agents, it's a form for submitting a ticket. 

If/when we have a real Residential MITx help center, we can link to that.

**Comment by tasawernawaz** [comment]
@pdpinch can we ask devops to set `SUPPORT_SITE_LINK` through configurations to fix 'Not Found' error.

**Comment by tasawernawaz** [comment]
Just realized that this is assigned to @rhysyngsun , I will remove this from my sprint tasks.

**Comment by shaidar** [comment]
Created [PR#775](https://github.com/mitodl/salt-ops/pull/775)

**Comment by shaidar** [comment]
Confirmed that QA build is working.
