### ISSUE TITLE
+New Course in Studio Causes Error

### ISSUE THREAD

**Issue by itsbenweeks** [mitodl/salt-ops#77]
Using the +New Course button from the Studio homepage after login will display a form. Completing the form leads to the new site's URL. This URL displays an error page. See https://studio-dogwood-qa-draft.mitx.mit.edu/course/MITx/Broken.Course/It_Is_Broken for an example.

**Comment by blarghmatey** [comment]
This was a result of a misnamed virtualhost in RabbitMQ which is now fixed.
