### ISSUE TITLE
Timed Exams do not work as expected.

### ISSUE THREAD

**Issue by itsbenweeks** [mitodl/salt-ops#78]
When trying to add a Timed Exam as outlined in the documentation, the option to add a timed exam is not available in a subsection's settings.

**Comment by pdpinch** [comment]
Can you post a link to the docs?

My first question is whether timed exams are supported in Dogwood. Second question is whether there is a feature flag or advanced setting that needs to be turned on.

Last question is whether they might require a split course?

**Comment by itsbenweeks** [comment]
1. The documentation at http://edx.readthedocs.io/projects/open-edx-ca/en/named-release-dogwood.rc/course_features/timed_exams.html#enable-timed-exams points you to the proper advanced setting, which is available within our implementation of Studio.
2. It may require a split course. That is not mentioned.

**Comment by blarghmatey** [comment]
@itsbenweeks I added a feature flag that should fix this and deployed it. Let me know if you continue to see problems with this feature.

**Comment by itsbenweeks** [comment]
I've been able to make timed exams work on this stack now.
