### ISSUE TITLE
Incorporate TestInfra into state module

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#8]
Write a state module for executing TestInfra tests against target nodes. This will make it simpler to propagate tests from formulas up to executing against target nodes at deployment time.

Refer to https://github.com/ssplatt/saltstack-infratest-module

Things to note:
- [ ] Ability to add plugins for TestInfra
- [ ] Explore possibility of extracting into a runner

**Comment by pdpinch** [comment]
What's the status of this?

**Comment by blarghmatey** [comment]
It is still in progress. I am working on unit tests for it, but at the moment it is functional as a module. The next step is to wrap it to be executed in a state context which should be fast to do.
