### ISSUE TITLE
Integrate MITxPro production Heroku and edX services

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#804]

**Comment by pdpinch** [comment]
> [sar [6:56 PM]](https://mitodl.slack.com/archives/G1VJQHQHK/p1556837762015700)
> It’s done as far as the heroku app, the openedx stack, and the Django admin config for both envs. A config update needs to be run against the openedx instances now that my PR has merged to add a few keys and testing the signup and registration workflow to verify that all is functional

**Comment by markbreedlove** [comment]
@shaidar and I have tested the registration workflow on QA and Production and have observed it working now, after he made some fixes.
