### ISSUE TITLE
Add UBC Peer Instruction XBlock

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#83]
See [Zenhub #3019](https://odl.zendesk.com/agent/tickets/3019)

seems like we can cherry-pick https://github.com/edx/edx-platform/commit/cffaa3ee6bc67fbd9f3c4fb94c73d0f27ae0d030

**Comment by blarghmatey** [comment]
Cherrypicked in mitodl/edx-platform#1

**Comment by pdpinch** [comment]
Hm. This isn't working for me. 

The cherry pick probably wasn't sufficient. Has "ubcpi" been added to `ADVANCED_COMPONENT_TYPES` somewhere?

To test this, I added "ubcpi" to the advanced settings in studio for [my test course](https://studio-dogwood-qa-draft.mitx.mit.edu/settings/advanced/MITx/TEST101/2014_Spring) but it doesn't appear in the list of advanced blocks in studio. 
 
Documentation for this xblock is pretty sparse. I can contact the developers if its helpful.

**Comment by pdpinch** [comment]
Although this xblock is [supported on edX](http://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/exercises_tools/peer_instruction_tool.html) it doesn't appear to be part of a standard edX configuration (for example, it's not available in devstack). This commit we cherry-picked seems to be only enough to get pypi to load the xblock on edx.org installs. 

I don't understand how the edX configuration overrides work, but I've created a branch that worked for me (I would have opened a PR but I'm not sure which base branch to use). 

In any case, if there's a more configuration-friendly way to do this, please feel free to do so. 

See  https://github.com/mitocw/edx-platform/tree/pdpinch/add-ubcpi-xblock

**Comment by pdpinch** [comment]
I can add a Peer Instruction xblock/unit now, but when I do I get the error:

```
Error: 'PeerInstructionXBlockWithMixins' object has no attribute 'ugettext'
```

This is similar to error we're seeing in #82 with LTI XBlocks. My first guess is it's a an xblock version dependency.

**Comment by pdpinch** [comment]
A requirement for xblock 0.4.7 was added in https://github.com/ubc/ubcpi/commit/d33048afeb7520ab564c3196329c6430c45fdb48

**Comment by pdpinch** [comment]
@blarghmatey let's try version 0.5.1 https://github.com/ubc/ubcpi/releases/tag/0.5.1

In its requirements, it pins an Xblock commit edx/xblock@017b46b80e712b1318379912257cf1cc1b68eb0e -- I'm not sure how to tell whether that's before or after the dogwood named release.

**Comment by itsbenweeks** [comment]
`git reflog | grep '017b46b'`

**Comment by blarghmatey** [comment]
This has been updated and installed. It should be ready for review again.

**Comment by pdpinch** [comment]
AFAICT, this is working. I'll follow up on ZenHub.
