### ISSUE TITLE
Add elastalert for session failures in edX

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#833]
When the Django app is unable to write to the Memcached layer it generates session errors that we would like to be notified of using Elastalert. The relevant message is found here: https://github.com/django/django/blob/master/django/contrib/sessions/middleware.py#L58-L65

**Comment by markbreedlove** [comment]
@blarghmatey Should this be for any environment other than `mitx-production`, or any fluentD tag other than `edx.lms`?

**Comment by blarghmatey** [comment]
This should apply to any production edX installation, so both residential and xpro. As to tags, it _might_ apply to edx.cms but lms is definitely the priority.

**Comment by markbreedlove** [comment]
PR #840 is merged and the Salt state has been run on Kibana.
