### ISSUE TITLE
Cherry-pick export fix that omits draft orphans

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#84]
See [ZenDesk 3417](https://odl.zendesk.com/agent/tickets/3417) for the use case. Trying to export https://studio-dogwood-qa-draft.mitx.mit.edu/export/MITX/18.06r_1/2015_Spring results in an error, `ValueError: BlockUsageLocator(CourseLocator(u'MITX', u'18.06r_1', u'2015_Spring', None, None), u'vertical', u'e8e8f99161484572b359bdff2b6e347a') is not in list`

We think applying https://github.com/edx/edx-platform/pull/12702 might address this.

**Comment by pdpinch** [comment]
I'm getting a different error now on attempting to export this course. I guess that means the cherry pick worked, but I'd like to leave this issue open until we get a clean export of this course.

**Comment by pdpinch** [comment]
Turns out I was exporting the wrong course in my tests of the cherry pick. 

@mitodl/devops should we revert this cherry pick?

**Comment by blarghmatey** [comment]
@pdpinch I think it's probably worth keeping it in so that we don't have to worry about the situation that it is intended to handle, though I'm happy to consider any other suggestions. @bdero ?

**Comment by pdpinch** [comment]
@bdero what do you think about this? Leave the cherry-pick or revert it?

**Comment by pdpinch** [comment]
Ok. Let's leave it.

**Comment by bdero** [comment]
I agree that we should keep it.

Apologies for missing this, emails for this conversation were getting incorrectly thrown into the promotions tab..
