### ISSUE TITLE
View Live Version button links in Studio to old stack.

### ISSUE THREAD

**Issue by itsbenweeks** [mitodl/salt-ops#85]
https://studio-dogwood-qa-draft.mitx.mit.edu/container/i4x://test_org/6.321/vertical/5ea6ec1cd3834b018e2f2d4d48a40147 press the blue *View Live Version* button and you will be directed to a -staging server.

**Comment by blarghmatey** [comment]
This looks to be working after the latest deploys.

**Comment by pdpinch** [comment]
@itsbenweeks can you confirm if this is working for you?

**Comment by itsbenweeks** [comment]
👌
