### ISSUE TITLE
Daemonize heroku proxy minions and schedule cred update

### ISSUE THREAD

**Issue by shaidar** [mitodl/salt-ops#857]
Proxy minions are currently being run only when needed on the salt-master. Downside to that is that AWS credentials used in Heroku need to be refreshed prior to expiration manually. We should daemonize the proxy minions on the salt-master and schedule the `heroku.update_heroku_config` state to run on a schedule.

**Comment by pdpinch** [comment]
@blarghmatey who will work on this?

**Comment by blarghmatey** [comment]
@shaidar or myself can take care of this. I will work with him to make sure it gets taken care of this sprint.

**Comment by shaidar** [comment]
Submitted [PR#905](https://github.com/mitodl/salt-ops/pull/905) to add open-discussions config vars to pillar.

**Comment by shaidar** [comment]
This has been deployed and scheduled on `xpro-ci` and `discussions-ci`. Will rollout out rc next week and then production.

**Comment by blarghmatey** [comment]
@shaidar is this complete now?

**Comment by shaidar** [comment]
Yes, closing
