### ISSUE TITLE
Migrate MM ES cluster to rc & production apps clusters

### ISSUE THREAD

**Issue by shaidar** [mitodl/salt-ops#867]
MM is using a single ES cluster with separate indices for all environments. We need to migrate the data to the `rc-apps` and `production-apps` ES clusters respectively.

**Comment by shaidar** [comment]
Below are the steps I think should be followed:
- rolling upgrade of 6.x release on rc (6.6.1) and then prod ES cluster (6.6.1) to [6.7.2](https://www.elastic.co/downloads/past-releases)
- install [elasticdump](https://www.npmjs.com/package/elasticdump) on MM ES cluster
- install [readonlyrest](https://readonlyrest.com/download/) (should already be installed as open uses it, but might need to update the version once ES is upgraded) on ES rc and prod clusters. 
- update pillar.elasticsearch.apps to point to new version of readonlyrest
- add settings from pillar.nginx.micromasters_es to pillar.nginx.apps_es
    - only missing thing is the _cluster endpoint and micromasters
- update pillar/top to remove elasticsearch-micromasters
- close all 'micromasters-ci-pr*' indices as no point in copying those over
- configure read-only rest for MM index (this looks like it's already in place - pillar.elasticsearch.apps)
- dump prod index to RC for testing

**Comment by blarghmatey** [comment]
Looks accurate to me.

**Comment by blarghmatey** [comment]
This is the detailed steps for completing mitodl/micromasters#3748
