### ISSUE TITLE
Restart residential workers after creds are updated

### ISSUE THREAD

**Issue by shaidar** [mitodl/salt-ops#868]
There's a scheduled task that runs on the residential worker instances every 5 days to update the credentials. However, that tasks does not restart the workers and when the credentials expire, even though they are not on disk, the worker process would still be using the expired credentials. We need to restart the worker processes so that they use the valid credentials.

**Comment by pdpinch** [comment]
This question is a digression, but what kind of monitoring do we have for the workers? Shouldn't there be an error and an alert when their credentials have expired?

**Comment by shaidar** [comment]
We have the usual monitoring as far as alerts being triggered based on Datadog metrics on those instances. There are also the elastalerts that are triggered, but doesn't appear that we have one for this particular case. Will get the logs and put in a PR for an alert related to this.

**Comment by shaidar** [comment]
The elastalert is more involved than I initially assumed as we are only shipping the logs under `/edx/var/log/{cms,lms}/edx.log` and the error is actually logged in one of the files under `/edx/var/log/supervisor/lms*-stderr.log`.
Will create a separate issue to track the alert and log shipping on the worker side.

**Comment by shaidar** [comment]
Deployed
