### ISSUE TITLE
setup xsiftx with dogwood

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#87]
As far as I can recall, there is an xsiftx module in the DevOps course. We should be able to use that for testing. 

@itsbenweeks do you know of anyone still using xsiftx in live courses?

**Comment by pdpinch** [comment]
@mitodl/devops 

As far as I can tell, this is Brandon's last remaining open issue. What's up with it?

**Comment by blarghmatey** [comment]
We need to all powwow on what sifters are still necessary.

On Aug 18, 2016 5:19 PM, Peter Pinch <notifications@github.com> wrote:

@mitodl/devops<https://github.com/orgs/mitodl/teams/devops>

As far as I can tell, this is Brandon's last remaining open issue. What's up with it?

**Comment by pdpinch** [comment]
Here's the list from last fall: https://github.mit.edu/mitx-devops/mitx-ansible/pull/125/files <https://github.mit.edu/mitx-devops/mitx-ansible/pull/125/files>

+ - "MITx/18.03r_2/2015_Fall"    
+ - "MITx/7.012r_1/2015_Fall"    
+ - "MITx/6.0001r_2/2015_Fall"    
+ - "MITX/18.06r_2/2015_Fall"    
+ - "MITx/15.401r/2015_Fall"    
+ - "MITx/6.042r_2/2015_Fall"    
+ - "MITx/8.01r_2/2015_Fall"    
+ - "MITx/5.111r_3/2015_Fall"    

We'll need to check to see if there are new runs for these courses & update the course id. 

We should add the 6.0001 ASE course and if there's a 6.0002 course we can add that as well. 

- Peter

**Comment by bdero** [comment]
Relevant zendesk ticket (from the last time we did this): https://odl.zendesk.com/agent/tickets/3018

I wrote this script to produce a histogram of course enrollments per course:

```python
from collections import defaultdict
import operator

from student.models import CourseEnrollment


enrollments = defaultdict(int)
for ce in CourseEnrollment.objects.all():
    if ce.is_active:
        enrollments[ce.course_id.__unicode__()] += 1

sorted_enrollments = sorted(enrollments.items(), key=operator.itemgetter(1), reverse=True)

print("Course-enrollment count map:")
for k, v in sorted_enrollments:
    print k, "::", v
```

**Comment by pdpinch** [comment]
but we won't have any enrollments until September

**Comment by bdero** [comment]
Yes, but it might be useful to check enrollments after the semester starts.

**Comment by blarghmatey** [comment]
Closing this ticket as complete because Xsiftx can be installed and configured. We will revisit the list of courses needing pre-computed grades as we get started with the semester.
