### ISSUE TITLE
IDDE: Extension Date Not Shown on Outline

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#872]
See https://github.mit.edu/mitx/Summer-2019/issues/2

This works in the current release (spring 2019) but not in the next (summer 2019). 

Presumably, we're missing some commits. The relevant edX PRs are: https://github.com/edx/edx-platform/pull/17451 and https://github.com/edx/edx-platform/pull/17682

**Comment by shaidar** [comment]
I checked and it appears that both of the commits linked above are actually running on the next residential instances.

**Comment by shaidar** [comment]
Done
