### ISSUE TITLE
Update RDS orchestration to use custom parameter group

### ISSUE THREAD

**Issue by shaidar** [mitodl/salt-ops#876]
Currently we're provisioning RDS instances with the default parameter group. We should create a custom one and use it when orchestrating RDS instances. One of the options we should set with a new parameter group is [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.SSL.Requiring)

**Comment by blarghmatey** [comment]
This is complete as part of the work to add read replicas to our running RDS instances.
