### ISSUE TITLE
AWS OCW: Fix course publish not filling in syllabus page

### ISSUE THREAD

**Issue by markbreedlove** [mitodl/salt-ops#881]
@JoeMartis ran a publish of a course in AWS production and the syllabus page of the course was an empty shell that looked like the home page.

**Comment by markbreedlove** [comment]
Hey, @JoeMartis, I should have thought of this earlier, but I am curious as to what happens if you try the same thing on AWS staging.

I tried creating a similar course in staging, but it won't give me any Course Owners to choose from, and Course Owner is a required field.  Maybe I'm doing something wrong.

**Comment by JoeMartis** [comment]
Ok, I will try it on AWS Staging.
Re: course owners - that is a matter of group permissions in CMS. I will add some users to the group.

**Comment by markbreedlove** [comment]
At about noon today I republished the page and the syllabus is filled in with the dummy content that @JoeMartis  added.

I re-published another course that had already been published. I was curious whether this would assemble some html fragments or assets or something that would allow the syllabus page to be filled in. I'm not sure if that was exactly the solution, but now the new course that Joe added has the syllabus intact.

I have a further followup task to have Nginx serve the `index.htm` page for a url that doesn't end in a slash, like `.../syllabus`. This is just a matter of getting the configuration on the production origin server to work like staging does.

**Comment by markbreedlove** [comment]
Nginx is fixed, now.
