### ISSUE TITLE
Create alerts for failed scheduled tasks

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#899]
In order to get better visibility into our automatic tasks we should set up some alerting for failed task runs that are executed as part of a Salt schedule.

**Comment by blarghmatey** [comment]
One possibility is to use the Sentry returner to log errors in Sentry when salt runs fail

https://docs.saltstack.com/en/latest/ref/returners/all/salt.returners.sentry_return.html#module-salt.returners.sentry_return

**Comment by shaidar** [comment]
Worth a look, but sounds like we should be using sentry_sdk as opposed to raven: https://docs.sentry.io/clients/python/

**Comment by shaidar** [comment]
Moving away from saltstack so closing this.
