### ISSUE TITLE
Prune old logging cluster indices

### ISSUE THREAD

**Issue by markbreedlove** [mitodl/salt-ops#912]
Old Elasticsearch indices are building up on the operations logging cluster. There are currently over 2.2K of them and the number of indices or the volume of data is starting to affect performance. Each of our products has an index for every day. Some products need more history, others less. MITx Residential needs the most history -- to the beginning of the past semester; others, like various QA services, need less.

Here are the general index prefix patterns with the earliest dates.

|pattern|earliest date|
|-----|-----|
|logstash-fluent|2019-01-01|
|logstash-heroku | 2019-01-01|
|logstash-mailgun | 2019-01-01|
|logstash-mitx-production | 2019-01-01|
|logstash-mitx-qa | 2019-01-01  (plus 2019-12-02 and 2019-12-10)|
|logstash-mitxpro-production | 2019-04-18|
|logstash-mitxpro-qa | 2019-01-30|
|logstash-ocw | 2019-04-23|
|logstash-ocw-production | 2019-03-13|
|logstash-ocw-qa | 2019-04-17|
|logstash-operations | 2019-01-01|
|logstash-production-apps | 2019-01-01|
|logstash-rc-apps | 2019-01-01|
|logstash-redash | 2019-01-02|
|logstash-saltmaster | 2019-01-01|

A. How long should we retain logs for each service?

B. Should I spend time on writing or installing some kind of index-pruning script to help with the task, or should I just delete these manually or semi-manually for now (with a one-off, hardcoded script)?

**Comment by blarghmatey** [comment]
The latest Kibana has a useful management UI for building index lifecycle policies which we should take advantage of to maintain our indices https://logs.odl.mit.edu/app/kibana#/management/elasticsearch/index_lifecycle_management/policies/edit
