### ISSUE TITLE
HLS Video Upload Configuration for OpenEdX/Studio

### ISSUE THREAD

**Issue by ahmed-arbisoft** [mitodl/salt-ops#947]
#### Related Issue
https://github.com/mitodl/mitxpro/issues/545
Adds support for importing existing HLS videos from the Video Upload screen in Studio.

#### Required Changes
- `admin/video_config/hlsplaybackenabledflag/` (`HLSPlaybackEnabledFlag`) should have one flag with `enabled=True` and optionally `enabled_for_all_courses=True` (If not enabled for all courses, a specific `CourseHLSPlaybackEnabledFlag` will need to be added for courses that we want to enable HLS uploads for.)
- `admin/video_pipeline/videouploadsenabledbydefault/` (`VideoUploadsEnabledByDefault`) should have one record with `enabled=True` and optionally `enabled_for_all_courses=True` (if not enabled for all courses, a specific `CourseVideoUploadsEnabledFlag` will need to be added for courses which need video uploads enabled.)
- Video pipeline should be configured.

**Comment by shaidar** [comment]
Those were already in place on CI and are now on RC and Production

**Comment by pdpinch** [comment]
AFAICT this all works.
