### ISSUE TITLE
Theme Footer Links Configuration

### ISSUE THREAD

**Issue by ahmed-arbisoft** [mitodl/salt-ops#948]
#### Relevant issue
https://github.com/mitodl/mitxpro/issues/820

#### Summary

Describe where/how to generate these new values

- `ENABLE_MKTG_SITE` - lms.env.json - Should be set to `True`
- `MARKETING_SITE_ROOT` - lms.env.json - Should be equal to `XPRO_BASE_URL` variable value
- `SUPPORT_SITE_LINK` - lms.env.json - Should be set to `https://xpro.zendesk.com/hc/`
- `MKTG_URLS['ABOUT']` - lms.env.json - Should be set to `/about-us`
- `MKTG_URLS['CONTACT']` - lms.env.json - Should be set to `https://xpro.zendesk.com/hc/en-us/requests/new`
- `MKTG_URLS['BLOG']`, `MKTG_URLS['DONATE']` - lms.env.json - Should be removed (these are links we don't want in the footer.)

#### Applicable Environments

- [x] Apply configuration to CI
- [x] Apply configuration to RC
- [x] Apply configuration to Production

**Comment by ahmed-arbisoft** [comment]
@pdpinch Please confirm if the required information is sufficient. Please bear in mind that the "Help Center ==> Support Center" change is done in the template so that needs no configuration changes.

**Comment by shaidar** [comment]
Deployed to sandbox

**Comment by shaidar** [comment]
Deployed to RC

**Comment by shaidar** [comment]
Deployed to production
