### ISSUE TITLE
Get SSL cert for ocw2.mit.edu

### ISSUE THREAD

**Issue by markbreedlove** [mitodl/salt-ops#949]
`ocw2.mit.edu` is http-only. This is because it had been configured that way before we migrated it over to AWS. We should get a certificate from IS&T and configure it the same way as production, where `http` redirects to `https`.

This will provide a more realistic staging environment (surfacing potential cross-origin issues with https, for instance) and will also make it easier to remember its URL, if it's consistent with all the other sites.

**Comment by shaidar** [comment]
@markbreedlove Am I wrong in assuming that you've already done this?

**Comment by markbreedlove** [comment]
No, I have not already done this.

**Comment by shaidar** [comment]
Assuming this has been taken care of and closing.

**Comment by markbreedlove** [comment]
I have not done it, but I'm creating a Trello card to replace this ticket.
