### ISSUE TITLE
xPro Course import fails

### ISSUE THREAD

**Issue by shaidar** [mitodl/salt-ops#950]
Importing a course on xpro-qa (/import/course-v1:TestX+AMxF+r2) fails after uploading about 6-7% of the course file. Error observed in CMS:
```
2019-07-25 15:31:54,333 WARNING 2996 [contentstore.views.import_export] import_export.py:168 - Reported range 40000000 does not match size downloaded so far 20000000
```
Tried importing same course into mitx-qa and that worked fine, so that rules out any issues with the course itself. Also verified that EFS config is correct and the is mounted on both instances. Additionally, I was able to import a smaller course without a problem so it appears to be some problem with the file size.

**Comment by shaidar** [comment]
Tried the import again and this time it worked. Not sure if it was some network issue or something else going on.

**Comment by pdpinch** [comment]
Can we close this?
