### ISSUE TITLE
OpenEdx Video Thumbnail Configuration

### ISSUE THREAD

**Issue by ahmed-arbisoft** [mitodl/salt-ops#962]
#### Relevant issue
https://github.com/mitodl/mitxpro/issues/544

#### Summary
Enables course video thumbnails on studio

- /admin/waffle/switch/ needs a switch added `videos.video_image_upload_enabled` in Studio admin

#### Applicable Environments

- [x] Apply configuration to CI
- [x] Apply configuration to RC
- [x] Apply configuration to Production

**Comment by shaidar** [comment]
Switch was already in place on CI and added to RC and production.

**Comment by pdpinch** [comment]
So we can "edit" and upload new thumbnails now, but the upload always fails. At least, for me, on CI, RC and production. 

See https://embed.vidyard.com/share/oHJ3eeqpJgpAjJvPX3WknK?

**Comment by pdpinch** [comment]
This appears to be working on all instances now.
