### ISSUE TITLE
Reconcile our fork of nginx-formula with upstream

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#980]
- [x] Pull upstream master into our fork
- [x] Update our pillar data as needed to comply with latest version

**Comment by blarghmatey** [comment]
@markbreedlove this is unblocked now and can be rebased and tested when ready so that we can validate it in our QA environment.

**Comment by markbreedlove** [comment]
Pull request: https://github.com/mitodl/nginx-formula/pull/2

**Comment by markbreedlove** [comment]
This is the other PR, for the pillar data: https://github.com/mitodl/salt-ops/pull/1099

**Comment by markbreedlove** [comment]
The PRs are merged.
