### ISSUE TITLE
Provision CloudFront distribution for xPRO application

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#988]
In order for us to add an MX record for xpro.mit.edu we first need to assign that domain to an A record. To achieve this we would like to deploy a Cloudfront distribution that uses a custom SSL domain and configure it to use the Heroku application as its origin.

**Comment by shaidar** [comment]
Requested SSL certs(RC and Prod) from IS&T for use on the Cloudfront distribution.

**Comment by shaidar** [comment]
Configured and tested CloudFront on RC and was in the process of configuring the production distribution when I realized that the IP assigned was not static based on our understanding of the `Dedicated IP` for the Cloudfront distribution. Reached out to AWS support and their explanation of dedicated IP states:

```The 'dedicated IP' does not mean that it is a static IP. It means that there will be one IP address at each edge location assigned to your CloudFront distribution from the pool of IP addresses. This IP address is not shared with any other distribution at the same time as when it is being used by your distribution. However, it may change as it is rotated frequently. At this time, there will be a new IP address assigned to your distribution  and this will again be dedicated and not shared with any other distribution.```

Given that Cloudfront doesn't provide us with a static IP, we are back to the drawing board on this.

**Comment by blarghmatey** [comment]
Closing this issue as Cloudfront is not going to work for our purposes. We can open a new issue to cover whichever option we decide on for next steps.
