### ISSUE TITLE
Speed up OCW CMS engine servers

### ISSUE THREAD

**Issue by markbreedlove** [mitodl/salt-ops#989]
Investigate a faster instance type (probably `z1d`).

Other things might help, too: placement groups, checking that enhanced networking is enabled, further tuning Zope memory and cache settings.

**Comment by markbreedlove** [comment]
I've been able to create a test `z1d.large` instance in our `us-east-1a` AZ, after creating a new subnet for this purpose.

**Comment by markbreedlove** [comment]
Benchmark, full-site republish, QA:

* staging publish: 8 days
* production publish: 21 hours

I'll run it next with the `z1d.large` replacement for the CMS-2 (engine) server.

**Comment by markbreedlove** [comment]
Looking at the statistics gathered by our new `netdata` service, CPU is clearly the bottleneck during the staging publish, and i/o wait for NFS activity (with Amazon's EFS)  is clearly the bottleneck during the production publish. (And the i/o wait for NFS is obviously a network bottleneck, if you'd like to look at it that way; but network latency that we can't avoid by tuning or selecting placement groups.) One way to avoid the NFS latency would be to get away from using the `/mnt/ocwfileshare` fileshare, but I don't think it makes sense to re-engineer that.

**Comment by markbreedlove** [comment]
Here is a comparison of the CPUs of the legacy and current CMS 2 (engine) servers. These are from `/proc/cpuinfo` on the relevant servers. The [bogomips](https://en.wikipedia.org/wiki/BogoMips) values are intended for comparing the relative speeds of different CPUs.

If the full site republish on the legacy system was faster, I think the CPU speed explains it, coupled with the fact that it was on dedicated hardware, as opposed to being a VM.

### Legacy (16 CPU cores, with each as follows):

model name	: Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz
bogomips	: 5320.04


### ocw-qa-cms-2 (2 CPU cores, as follows):

model name      : Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
bogomips        : 4600.12

### ocw-qa-cms-2b (2 CPU cores, as follows):

model name      : Intel(R) Xeon(R) Platinum 8151 CPU @ 3.40GHz
bogomips        : 6800.00

**Comment by markbreedlove** [comment]
Benchmark, full-site republish, QA, `z1d.large` instance type:

* staging publish: 5 days
* production publish: 21 hours

The staging publish is fast enough to justify switching to this new instance type.

The work to do the cutover shouldn't be too disruptive. The worst part will be taking down plone for a while in order to get a clean snapshot of the filesystem.   @JoeMartis Do you think there will be a time soon when I can have the engines offline for an hour or so to make a filesystem snapshot? I can leave the CMS up.

After the snapshot is taken, the actual cutover should cause no interruption.

**Comment by JoeMartis** [comment]
Hi Mark – Do you ONLY need to disable the engines? i.e. will everything else work as expected during this time? Can people continue to use the system, or do they need to be out entirely?

Thank you,
Joe

**Comment by markbreedlove** [comment]
@JoeMartis Only the engines would be stopped. They could keep working in the CMS on content.

**Comment by JoeMartis** [comment]
Cool – we can do it at any time then, I just have to let folks know that the staging engine will be unavailable.

Do you want to pick a date/time and I will notify?

Thanks,
Joe

**Comment by markbreedlove** [comment]
Sure, would now be OK?

**Comment by JoeMartis** [comment]
Gimme 10 minutes to warn folks.
