### ISSUE TITLE
Configure OpenEdX Grades API Service User Token

### ISSUE THREAD

**Issue by ahmed-arbisoft** [mitodl/salt-ops#995]
#### Relevant issue
https://github.com/mitodl/mitxpro/issues/1029

#### Summary
Courses grade/certificate sync command needs to fetch grades from the OpenEdX API. Following value needs to be set:

- `OPENEDX_GRADES_API_TOKEN` environment variable should be set to an access token that has authorization to get course grades from the linked OpenEdX instance.

#### Applicable Environments

- [x] Apply configuration to CI
- [x] Apply configuration to RC
- [x] Apply configuration to Production

**Comment by pdpinch** [comment]
@ahmed-arbisoft is this working OK on RC now? Please let @shaidar know if you we can deploy to production.

**Comment by ahmed-arbisoft** [comment]
@pdpinch someone will need to verify the command is working on RC. I think it was @gsidebo who tested my deployment on RC because I didn't have access to the heroku shell in order to test the management command.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub (https://link.getmailspring.com/link/10871F65-15B8-43A7-B253-36E0AD24F686@getmailspring.com/0?redirect=https%3A%2F%2Fgithub.com%2Fmitodl%2Fsalt-ops%2Fissues%2F995%3Femail_source%3Dnotifications%26email_token%3DAKZ74EXBZPRGLDWI6WXVYJLQJPGCDA5CNFSM4IRIYLT2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6VWXJY%23issuecomment-531327911&recipient=cmVwbHkrQUtaNzRFUjY1RDI0MlFQS0NDQUk1RTUzUkVLVERFVkJOSEhCWjdSWEpVQHJlcGx5LmdpdGh1Yi5jb20%3D), or mute the thread (https://link.getmailspring.com/link/10871F65-15B8-43A7-B253-36E0AD24F686@getmailspring.com/1?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKZ74EQLEQSXJPEODOA6ECDQJPGCDANCNFSM4IRIYLTQ&recipient=cmVwbHkrQUtaNzRFUjY1RDI0MlFQS0NDQUk1RTUzUkVLVERFVkJOSEhCWjdSWEpVQHJlcGx5LmdpdGh1Yi5jb20%3D).
>
>


-- 


The content of this email and attachment(s) are confidential and intended 
solely for the recipient(s) specified in the message. If you received this 
email by error, please alert the sender by replying to this email and 
follow with its deletion, so that we can ensure such an error does not 
occur in future. If you are not the intended recipient, you are strictly 
prohibited to use, copy, disseminate or store this email or its 
attachment(s).

**Comment by asadiqbal08** [comment]
guys, any update over it ?

**Comment by gsidebo** [comment]
@shaidar I just confirmed that grades are being successfully fetched in RC, and that the management command is working as expected. If I'm not missing any verification steps, I think this is good to merge 👍

**Comment by shaidar** [comment]
@gsidebo That should be set on production now.
